#ifdef WIN32
    // Why?
    #define _WIN32_WINNT 0x0502
    // The standard Windows includes.
    #ifndef WIN32_LEAN_AND_MEAN
    #define WIN32_LEAN_AND_MEAN
    #endif // WIN32_LEAN_AND_MEAN
    #ifndef NOMINMAX
    #define NOMINMAX
    #endif // NOMINMAX
    #include <Windows.h>
    #include <wchar.h>
    #ifdef SLIC3R_GUI
    extern "C" 
    { 
        // Let the NVIDIA and AMD know we want to use their graphics card
        // on a dual graphics card system.
        __declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
        __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
    }
    #endif /* SLIC3R_GUI */
#endif /* WIN32 */

#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem.hpp>
#include <boost/nowide/args.hpp>
#include <boost/nowide/cenv.hpp>
#include <boost/nowide/fstream.hpp>
#include <boost/nowide/iostream.hpp>
#include <boost/nowide/integration/filesystem.hpp>
#include <boost/dll/runtime_symbol_info.hpp>

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <limits>
#include <map>
#include <memory>
#include <set>
#include <sstream>

#include "unix/fhs.hpp"  // Generated by CMake from ../platform/unix/fhs.hpp.in

#include "libslic3r/libslic3r.h"
#if ENABLE_GL_CORE_PROFILE
#include <boost/algorithm/string/split.hpp>
#endif // ENABLE_GL_CORE_PROFILE
#include "libslic3r/AppConfig.hpp"
#include "libslic3r/Config.hpp"
#include "libslic3r/ExtrusionRole.hpp"
#include "libslic3r/Geometry.hpp"
#include "libslic3r/GCode/GCodeProcessor.hpp"
#include "libslic3r/GCode/PostProcessor.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/PresetBundle.hpp"
#include "libslic3r/CutUtils.hpp"
#include "libslic3r/ModelArrange.hpp"
#include "libslic3r/Platform.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/SLAPrint.hpp"
#include "libslic3r/TriangleMesh.hpp"
#include "libslic3r/Format/AMF.hpp"
#include "libslic3r/Format/3mf.hpp"
#include "libslic3r/Format/STL.hpp"
#include "libslic3r/Format/OBJ.hpp"
#include "libslic3r/Format/SL1.hpp"
#include "libslic3r/Format/CWS.hpp"
#include "libslic3r/PrintConfig.hpp"
#include "libslic3r/Utils.hpp"
#include "libslic3r/Thread.hpp"
#include "libslic3r/BlacklistedLibraryCheck.hpp"

#include "PrusaSlicer.hpp"

#ifdef SLIC3R_GUI
    #include "slic3r/GUI/GUI_Init.hpp"
#endif /* SLIC3R_GUI */

using namespace Slic3r;

namespace {

std::string json_escape(const std::string &value)
{
    std::ostringstream out;
    for (const unsigned char ch : value) {
        switch (ch) {
        case '"':  out << "\\\""; break;
        case '\\': out << "\\\\"; break;
        case '\b': out << "\\b"; break;
        case '\f': out << "\\f"; break;
        case '\n': out << "\\n"; break;
        case '\r': out << "\\r"; break;
        case '\t': out << "\\t"; break;
        default:
            if (ch < 0x20)
                out << "\\u" << std::hex << std::setw(4) << std::setfill('0') << int(ch) << std::dec;
            else
                out << char(ch);
        }
    }
    return out.str();
}

bool select_profile(PresetCollection &collection, const std::string &name, const char *kind, std::string &error)
{
    if (name.empty())
        return true;
    if (collection.find_preset(name, false, false) == nullptr) {
        error = std::string("Installed ") + kind + " profile not found: " + name;
        return false;
    }
    collection.select_preset_by_name(name, true);
    return true;
}

bool user_profiles_requested(const DynamicPrintAndCLIConfig &config)
{
    return config.opt_bool("load_user_profiles") ||
        config.opt_bool("list_profiles") ||
        !config.opt_string("printer_profile").empty() ||
        !config.opt_string("print_profile").empty() ||
        !config.opt_string("material_profile").empty();
}

std::string default_user_data_dir()
{
#ifdef _WIN32
    const char *root = boost::nowide::getenv("APPDATA");
    return root == nullptr ? std::string() : (boost::filesystem::path(root) / SLIC3R_APP_KEY).string();
#elif defined(__APPLE__)
    const char *home = boost::nowide::getenv("HOME");
    return home == nullptr ? std::string() :
        (boost::filesystem::path(home) / "Library" / "Application Support" / SLIC3R_APP_KEY).string();
#else
    if (const char *xdg_config_home = boost::nowide::getenv("XDG_CONFIG_HOME");
        xdg_config_home != nullptr && *xdg_config_home != '\0')
        return (boost::filesystem::path(xdg_config_home) / SLIC3R_APP_KEY).string();
    const char *home = boost::nowide::getenv("HOME");
    return home == nullptr ? std::string() :
        (boost::filesystem::path(home) / ".config" / SLIC3R_APP_KEY).string();
#endif
}

bool initialize_user_data_dir(AppConfig &app_config, std::string &error)
{
    if (has_data_dir())
        return true;

    const std::string root = default_user_data_dir();
    if (root.empty()) {
        error = "Unable to locate the user configuration directory; pass --datadir explicitly.";
        return false;
    }

    app_config.init_root_data_dir(root);
    if (has_data_dir())
        return true;

    const AppConfig::ConfigurationEntry *best = nullptr;
    for (const AppConfig::ConfigurationEntry &entry : app_config.get_all_slicer_installed()) {
        const boost::filesystem::path path = entry.get_config_path(app_config.get_root_data_dir());
        if (!boost::filesystem::is_directory(path))
            continue;
        if (best == nullptr ||
            (best->version != Semver(SLIC3R_VERSION_FULL) && entry.version == Semver(SLIC3R_VERSION_FULL)) ||
            (best->version != Semver(SLIC3R_VERSION_FULL) && entry.version > best->version))
            best = &entry;
    }

    if (best == nullptr) {
        error = "No installed SuperSlicer user configuration was found; pass --datadir explicitly.";
        return false;
    }

    set_data_dir(best->get_config_path(app_config.get_root_data_dir()).string());
    return true;
}

std::unique_ptr<PresetBundle> load_user_profiles(
    const DynamicPrintAndCLIConfig &config,
    ForwardCompatibilitySubstitutionRule compatibility_rule,
    std::string &error)
{
    try {
        AppConfig app_config(AppConfig::EAppMode::Editor);
        if (!initialize_user_data_dir(app_config, error))
            return {};
        if (std::string load_error = app_config.load(); !load_error.empty()) {
            error = "Unable to load the user application configuration: " + load_error;
            return {};
        }

        auto bundle = std::make_unique<PresetBundle>();
        bundle->load_presets(app_config, compatibility_rule);

        if (!select_profile(bundle->printers, config.opt_string("printer_profile"), "printer", error))
            return {};
        bundle->update_multi_material_filament_presets();
        bundle->update_compatible(PresetSelectCompatibleType::Always);

        const PrinterTechnology technology = bundle->printers.get_edited_preset().printer_technology();
        if (!select_profile(bundle->prints(technology), config.opt_string("print_profile"), "print", error))
            return {};

        const std::string material_name = config.opt_string("material_profile");
        if (!select_profile(bundle->materials(technology), material_name,
                technology == ptFFF ? "filament" : "SLA material", error))
            return {};
        if (technology == ptFFF && !material_name.empty())
            bundle->set_filament_preset(0, material_name);

        bundle->update_compatible(PresetSelectCompatibleType::Never);
        return bundle;
    } catch (const std::exception &ex) {
        error = ex.what();
        return {};
    }
}

void write_profile_collection_json(
    std::ostream &out,
    const PresetCollection &collection,
    const std::string &selected_name)
{
    out << "[";
    bool first = true;
    for (const Preset &preset : collection.get_presets()) {
        if (!first)
            out << ",";
        first = false;
        out << "{"
            << "\"name\":\"" << json_escape(preset.name) << "\","
            << "\"selected\":" << (preset.name == selected_name ? "true" : "false") << ","
            << "\"visible\":" << (preset.is_visible ? "true" : "false") << ","
            << "\"compatible\":" << (preset.is_compatible ? "true" : "false") << ","
            << "\"source\":\"" << (preset.is_default ? "default" : preset.is_system ? "system" : "user") << "\""
            << "}";
    }
    out << "]";
}

void write_profiles_json(std::ostream &out, const PresetBundle &bundle)
{
    out << "{\"schemaVersion\":1,\"active\":{"
        << "\"printer\":\"" << json_escape(bundle.printers.get_selected_preset_name()) << "\","
        << "\"fffPrint\":\"" << json_escape(bundle.fff_prints.get_selected_preset_name()) << "\","
        << "\"slaPrint\":\"" << json_escape(bundle.sla_prints.get_selected_preset_name()) << "\","
        << "\"filament\":\"" << json_escape(bundle.filaments.get_selected_preset_name()) << "\","
        << "\"slaMaterial\":\"" << json_escape(bundle.sla_materials.get_selected_preset_name()) << "\"},";
    out << "\"printers\":";
    write_profile_collection_json(out, bundle.printers, bundle.printers.get_selected_preset_name());
    out << ",\"fffPrints\":";
    write_profile_collection_json(out, bundle.fff_prints, bundle.fff_prints.get_selected_preset_name());
    out << ",\"slaPrints\":";
    write_profile_collection_json(out, bundle.sla_prints, bundle.sla_prints.get_selected_preset_name());
    out << ",\"filaments\":";
    write_profile_collection_json(out, bundle.filaments, bundle.filaments.get_selected_preset_name());
    out << ",\"slaMaterials\":";
    write_profile_collection_json(out, bundle.sla_materials, bundle.sla_materials.get_selected_preset_name());
    out << "}\n";
    out.flush();
}

struct LayerReport
{
    uint16_t id { 0 };
    float z { 0.0f };
    size_t move_count { 0 };
    size_t extrusion_moves { 0 };
    size_t travel_moves { 0 };
    double toolpath_length_mm { 0.0 };
    size_t tool_changes { 0 };
    std::set<uint8_t> extruders;
    std::map<std::string, size_t> roles;
};

std::map<uint16_t, LayerReport> build_layer_reports(const GCodeProcessorResult &result)
{
    std::map<uint16_t, LayerReport> layers;
    for (size_t index = 1; index < result.moves.size(); ++index) {
        const GCodeProcessorResult::MoveVertex &move = result.moves[index];
        if (move.type == EMoveType::Tool_change) {
            ++layers[move.layer_id].tool_changes;
            continue;
        }
        if (move.type != EMoveType::Extrude && move.type != EMoveType::Travel && move.type != EMoveType::Wipe)
            continue;

        LayerReport &layer = layers[move.layer_id];
        layer.id = move.layer_id;
        layer.z = move.position.z();
        ++layer.move_count;
        if (move.type == EMoveType::Extrude) {
            ++layer.extrusion_moves;
            layer.extruders.insert(move.extruder_id);
            ++layer.roles[gcode_extrusion_role_to_string(move.extrusion_role)];
            const Vec3f delta = move.position - result.moves[index - 1].position;
            layer.toolpath_length_mm += std::hypot(double(delta.x()), double(delta.y()));
        } else if (move.type == EMoveType::Travel) {
            ++layer.travel_moves;
        }
    }
    return layers;
}

bool ensure_output_parent(const std::string &path, std::string &error)
{
    try {
        const boost::filesystem::path parent = boost::filesystem::path(path).parent_path();
        if (!parent.empty())
            boost::filesystem::create_directories(parent);
        return true;
    } catch (const std::exception &ex) {
        error = ex.what();
        return false;
    }
}

bool write_slice_report(
    const GCodeProcessorResult &result,
    const DynamicPrintConfig &config,
    const std::string &path,
    std::string &error)
{
    if (!ensure_output_parent(path, error))
        return false;
    boost::nowide::ofstream out(path);
    if (!out) {
        error = "Unable to open slice report for writing: " + path;
        return false;
    }

    const std::map<uint16_t, LayerReport> layers = build_layer_reports(result);
    float min_x = std::numeric_limits<float>::infinity();
    float min_y = std::numeric_limits<float>::infinity();
    float max_x = -std::numeric_limits<float>::infinity();
    float max_y = -std::numeric_limits<float>::infinity();
    size_t extrusion_move_count = 0;
    size_t tool_change_count = 0;
    std::set<uint8_t> used_extruders;
    for (const GCodeProcessorResult::MoveVertex &move : result.moves) {
        if (move.type == EMoveType::Tool_change)
            ++tool_change_count;
        if (move.type != EMoveType::Extrude)
            continue;
        ++extrusion_move_count;
        used_extruders.insert(move.extruder_id);
        min_x = std::min(min_x, move.position.x());
        min_y = std::min(min_y, move.position.y());
        max_x = std::max(max_x, move.position.x());
        max_y = std::max(max_y, move.position.y());
    }

    std::string printer_profile = result.settings_ids.printer;
    std::string print_profile = result.settings_ids.print;
    std::vector<std::string> filament_profiles = result.settings_ids.filament;
    if (printer_profile.empty())
        if (const auto *option = config.option<ConfigOptionString>("printer_settings_id"); option != nullptr)
            printer_profile = option->value;
    if (print_profile.empty())
        if (const auto *option = config.option<ConfigOptionString>("print_settings_id"); option != nullptr)
            print_profile = option->value;
    if (filament_profiles.empty())
        if (const auto *option = config.option<ConfigOptionStrings>("filament_settings_id"); option != nullptr)
            filament_profiles = option->get_values();

    out << std::fixed << std::setprecision(6)
        << "{\"schemaVersion\":1,"
        << "\"gcode\":\"" << json_escape(result.filename) << "\","
        << "\"profiles\":{\"printer\":\"" << json_escape(printer_profile)
        << "\",\"print\":\"" << json_escape(print_profile) << "\",\"filaments\":[";
    for (size_t index = 0; index < filament_profiles.size(); ++index) {
        if (index != 0)
            out << ",";
        out << "\"" << json_escape(filament_profiles[index]) << "\"";
    }
    out << "]},\"summary\":{"
        << "\"layerCount\":" << layers.size() << ","
        << "\"moveCount\":" << result.moves.size() << ","
        << "\"extrusionMoveCount\":" << extrusion_move_count << ","
        << "\"estimatedTimeSeconds\":"
        << result.print_statistics.modes[size_t(PrintEstimatedStatistics::ETimeMode::Normal)].time << ","
        << "\"toolChangeCount\":" << tool_change_count << ","
        << "\"usedExtruders\":[";
    for (auto it = used_extruders.begin(); it != used_extruders.end(); ++it)
        out << (it == used_extruders.begin() ? "" : ",") << int(*it);
    out << "]},"
        << "\"bounds\":";
    if (extrusion_move_count == 0)
        out << "null";
    else
        out << "{\"minX\":" << min_x << ",\"minY\":" << min_y
            << ",\"maxX\":" << max_x << ",\"maxY\":" << max_y << "}";

    out << ",\"bedShape\":[";
    for (size_t index = 0; index < result.bed_shape.size(); ++index) {
        if (index != 0)
            out << ",";
        out << "[" << result.bed_shape[index].x() << "," << result.bed_shape[index].y() << "]";
    }
    out << "],\"layers\":[";
    bool first_layer = true;
    for (const auto &[id, layer] : layers) {
        if (!first_layer)
            out << ",";
        first_layer = false;
        out << "{\"id\":" << id << ",\"z\":" << layer.z
            << ",\"moveCount\":" << layer.move_count
            << ",\"extrusionMoves\":" << layer.extrusion_moves
            << ",\"travelMoves\":" << layer.travel_moves
            << ",\"toolpathLengthMm\":" << layer.toolpath_length_mm
            << ",\"toolChanges\":" << layer.tool_changes
            << ",\"extruders\":[";
        for (auto it = layer.extruders.begin(); it != layer.extruders.end(); ++it)
            out << (it == layer.extruders.begin() ? "" : ",") << int(*it);
        out << "],\"roles\":{";
        bool first_role = true;
        for (const auto &[role, count] : layer.roles) {
            if (!first_role)
                out << ",";
            first_role = false;
            out << "\"" << json_escape(role) << "\":" << count;
        }
        out << "}}";
    }
    out << "]}\n";
    return true;
}

const char *role_color(GCodeExtrusionRole role)
{
    switch (role) {
    case GCodeExtrusionRole::ExternalPerimeter:        return "#ef4444";
    case GCodeExtrusionRole::Perimeter:                return "#f97316";
    case GCodeExtrusionRole::OverhangPerimeter:        return "#ec4899";
    case GCodeExtrusionRole::InternalInfill:           return "#3b82f6";
    case GCodeExtrusionRole::SolidInfill:              return "#06b6d4";
    case GCodeExtrusionRole::TopSolidInfill:           return "#14b8a6";
    case GCodeExtrusionRole::BridgeInfill:
    case GCodeExtrusionRole::InternalBridgeInfill:     return "#8b5cf6";
    case GCodeExtrusionRole::SupportMaterial:          return "#84cc16";
    case GCodeExtrusionRole::SupportMaterialInterface: return "#22c55e";
    case GCodeExtrusionRole::Skirt:                    return "#eab308";
    case GCodeExtrusionRole::GapFill:
    case GCodeExtrusionRole::ThinWall:                 return "#f59e0b";
    case GCodeExtrusionRole::WipeTower:                return "#64748b";
    default:                                           return "#94a3b8";
    }
}

bool write_slice_preview(
    const GCodeProcessorResult &result,
    const std::string &path,
    int requested_layer,
    std::string &error)
{
    std::set<uint16_t> extrusion_layers;
    for (const GCodeProcessorResult::MoveVertex &move : result.moves)
        if (move.type == EMoveType::Extrude)
            extrusion_layers.insert(move.layer_id);
    if (extrusion_layers.empty()) {
        error = "The processed G-code contains no extrusion layers.";
        return false;
    }

    uint16_t layer_id = 0;
    if (requested_layer < 0) {
        auto middle = extrusion_layers.begin();
        std::advance(middle, extrusion_layers.size() / 2);
        layer_id = *middle;
    } else if (requested_layer > std::numeric_limits<uint16_t>::max() ||
               extrusion_layers.count(uint16_t(requested_layer)) == 0) {
        error = "Requested preview layer is not present in the processed G-code: " + std::to_string(requested_layer);
        return false;
    } else {
        layer_id = uint16_t(requested_layer);
    }

    float min_x = std::numeric_limits<float>::infinity();
    float min_y = std::numeric_limits<float>::infinity();
    float max_x = -std::numeric_limits<float>::infinity();
    float max_y = -std::numeric_limits<float>::infinity();
    float layer_z = 0.0f;
    for (size_t index = 1; index < result.moves.size(); ++index) {
        const GCodeProcessorResult::MoveVertex &move = result.moves[index];
        if (move.type != EMoveType::Extrude || move.layer_id != layer_id)
            continue;
        const Vec3f &start = result.moves[index - 1].position;
        min_x = std::min({ min_x, start.x(), move.position.x() });
        min_y = std::min({ min_y, start.y(), move.position.y() });
        max_x = std::max({ max_x, start.x(), move.position.x() });
        max_y = std::max({ max_y, start.y(), move.position.y() });
        layer_z = move.position.z();
    }

    if (!ensure_output_parent(path, error))
        return false;
    boost::nowide::ofstream out(path);
    if (!out) {
        error = "Unable to open slice preview for writing: " + path;
        return false;
    }

    const float content_width = std::max(max_x - min_x, 1.0f);
    const float content_height = std::max(max_y - min_y, 1.0f);
    const float padding = std::max(content_width, content_height) * 0.04f;
    const float view_min_x = min_x - padding;
    const float view_min_y = min_y - padding;
    const float view_width = content_width + 2.0f * padding;
    const float view_height = content_height + 2.0f * padding;

    out << std::fixed << std::setprecision(4)
        << "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"" << view_min_x << " " << view_min_y
        << " " << view_width << " " << view_height << "\" width=\"1000\" height=\"1000\">\n"
        << "<title>SuperSlicer layer " << layer_id << " at Z " << layer_z << " mm</title>\n"
        << "<rect x=\"" << view_min_x << "\" y=\"" << view_min_y << "\" width=\"" << view_width
        << "\" height=\"" << view_height << "\" fill=\"#0f172a\"/>\n"
        << "<g transform=\"translate(0 " << (min_y + max_y) << ") scale(1 -1)\" "
        << "stroke-linecap=\"round\" stroke-linejoin=\"round\" fill=\"none\">\n";
    for (size_t index = 1; index < result.moves.size(); ++index) {
        const GCodeProcessorResult::MoveVertex &move = result.moves[index];
        if (move.type != EMoveType::Extrude || move.layer_id != layer_id)
            continue;
        const Vec3f &start = result.moves[index - 1].position;
        const float width = std::clamp(move.width, 0.08f, 2.0f);
        out << "<line x1=\"" << start.x() << "\" y1=\"" << start.y()
            << "\" x2=\"" << move.position.x() << "\" y2=\"" << move.position.y()
            << "\" stroke=\"" << role_color(move.extrusion_role) << "\" stroke-width=\"" << width << "\"/>\n";
    }
    out << "</g>\n</svg>\n";
    return true;
}

} // namespace

static PrinterTechnology get_printer_technology(const DynamicConfig &config)
{
    const ConfigOptionEnum<PrinterTechnology> *opt = config.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
    return (opt == nullptr) ? ptUnknown : opt->value;
}

int CLI::run(int argc, char **argv)
{
    // Mark the main thread for the debugger and for runtime checks.
    set_current_thread_name("slic3r_main");
    // Save the thread ID of the main thread.
    save_main_thread_id();

    //init random generator
    std::srand((unsigned int)std::time(nullptr));

#ifdef __WXGTK__
    // On Linux, wxGTK has no support for Wayland, and the app crashes on
    // startup if gtk3 is used. This env var has to be set explicitly to
    // instruct the window manager to fall back to X server mode.
    ::setenv("GDK_BACKEND", "x11", /* replace */ true);
#endif

	// Switch boost::filesystem to utf8.
    try {
        boost::nowide::nowide_filesystem();
    } catch (const std::runtime_error& ex) {
        std::string caption = std::string(SLIC3R_APP_NAME) + " Error";
        std::string text = std::string("An error occured while setting up locale.\n") + (
#if !defined(_WIN32) && !defined(__APPLE__)
        	// likely some linux system
        	"You may need to reconfigure the missing locales, likely by running the \"locale-gen\" and \"dpkg-reconfigure locales\" commands.\n"
#endif
        	SLIC3R_APP_NAME " will now terminate.\n\n") + ex.what();
    #if defined(_WIN32) && defined(SLIC3R_GUI)
        if (m_actions.empty())
        	// Empty actions means Slicer is executed in the GUI mode. Show a GUI message.
            MessageBoxA(NULL, text.c_str(), caption.c_str(), MB_OK | MB_ICONERROR);
    #endif
        boost::nowide::cerr << text.c_str() << std::endl;
        return 1;
    }

	if (! this->setup(argc, argv))
		return 1;

    m_extra_config.apply(m_config, true);
    m_extra_config.normalize_fdm();
    
    PrinterTechnology printer_technology = get_printer_technology(m_config);

    bool							start_gui			= m_actions.empty() &&
        // cutting transformations are setting an "export" action.
        std::find(m_transforms.begin(), m_transforms.end(), "cut") == m_transforms.end() &&
        std::find(m_transforms.begin(), m_transforms.end(), "cut_x") == m_transforms.end() &&
        std::find(m_transforms.begin(), m_transforms.end(), "cut_y") == m_transforms.end();
    bool                            start_downloader = false;
    bool                            delete_after_load = false;
    std::string                     download_url;
    bool 							start_as_gcodeviewer =
#ifdef _WIN32
            false;
#else
            // On Unix systems, the superslicer binary may be symlinked to give the application a different meaning.
            boost::algorithm::iends_with(boost::filesystem::path(argv[0]).filename().string(), GCODEVIEWER_APP_CMD);
#endif // _WIN32

    const std::vector<std::string>              &load_configs		      = m_config.option<ConfigOptionStrings>("load", true)->get_values();
    const ForwardCompatibilitySubstitutionRule   config_substitution_rule = m_config.option<ConfigOptionEnum<ForwardCompatibilitySubstitutionRule>>("config_compatibility", true)->value;

    std::unique_ptr<PresetBundle> user_profiles;
    if (user_profiles_requested(m_config)) {
        std::string profile_error;
        user_profiles = load_user_profiles(m_config, config_substitution_rule, profile_error);
        if (!user_profiles) {
            boost::nowide::cerr << "Error while loading user profiles: " << profile_error << std::endl;
            return 1;
        }
        m_print_config.apply(user_profiles->full_config());
        if (printer_technology == ptUnknown)
            printer_technology = user_profiles->printers.get_edited_preset().printer_technology();
    }

    // load config files supplied via --load
    for (auto const &file : load_configs) {
        if (! boost::filesystem::exists(file)) {
            if (m_config.opt_bool("ignore_nonexistent_config")) {
                continue;
            } else {
                boost::nowide::cerr << "No such file: " << file << std::endl;
                return 1;
            }
        }
        DynamicPrintConfig  config;
        ConfigSubstitutions config_substitutions;
        try {
            config_substitutions = config.load(file, config_substitution_rule);
        } catch (std::exception &ex) {
            boost::nowide::cerr << "Error while reading config file \"" << file << "\": " << ex.what() << std::endl;
            return 1;
        }
        if (! config_substitutions.empty()) {
            boost::nowide::cout << "The following configuration values were substituted when loading \" << file << \":\n";
            for (const ConfigSubstitution &subst : config_substitutions)
                if(subst.opt_def)
                    boost::nowide::cout << "\tkey = \"" << subst.opt_def->opt_key << "\"\t loaded = \"" << subst.old_value << "\tsubstituted = \"" << subst.new_value->serialize() << "\"\n";
                else
                    boost::nowide::cout << "\tkey = \"" << subst.old_name << "\"\t can't be loaded (value = \"" << subst.old_value <<"\")\n";
        }
        config.normalize_fdm();
        PrinterTechnology other_printer_technology = get_printer_technology(config);
        if (printer_technology == ptUnknown) {
            printer_technology = other_printer_technology;
        } else if (printer_technology != other_printer_technology && other_printer_technology != ptUnknown) {
            boost::nowide::cerr << "Mixing configurations for FFF and SLA technologies" << std::endl;
            return 1;
        }
        m_print_config.apply(config);
    }
        
#ifdef SLIC3R_GUI
#if ENABLE_GL_CORE_PROFILE
    std::pair<int, int> opengl_version = { 0, 0 };
    bool                opengl_debug = false;
    bool                opengl_compatibility_profile = false;

    // search for special keys into command line parameters
    auto it = std::find(m_actions.begin(), m_actions.end(), "gcodeviewer");
    if (it != m_actions.end()) {
        start_gui = true;
        start_as_gcodeviewer = true;
        m_actions.erase(it);
    }

    it = std::find(m_actions.begin(), m_actions.end(), "opengl-version");
    if (it != m_actions.end()) {
        const Semver opengl_minimum = Semver(3,2,0,0);
        const std::string opengl_version_str = m_config.opt_string("opengl-version");
        std::optional<Semver> semver = Semver::parse(opengl_version_str);
        if (semver.has_value() && (*semver) >= opengl_minimum ) {
            opengl_version.first = semver->maj();
            opengl_version.second = semver->min();
            if (std::find(Slic3r::GUI::OpenGLVersions::core.begin(), Slic3r::GUI::OpenGLVersions::core.end(), std::make_pair(opengl_version.first, opengl_version.second)) == Slic3r::GUI::OpenGLVersions::core.end()) {
                opengl_version = { 0, 0 };
                boost::nowide::cerr << "Required OpenGL version " << opengl_version_str << " not recognized.\n Option 'opengl-version' ignored." << std::endl;
            }
        } else
            boost::nowide::cerr << "Required OpenGL version " << opengl_version_str << " is invalid. Must be greater than or equal to " <<
                opengl_minimum.to_string() << "\n Option 'opengl-version' ignored." << std::endl;
        start_gui = true;
        m_actions.erase(it);
    }

    it = std::find(m_actions.begin(), m_actions.end(), "opengl-compatibility");
    if (it != m_actions.end()) {
        start_gui = true;
        opengl_compatibility_profile = true;
        // reset version as compatibility profile always take the highest version
        // supported by the graphic card
        opengl_version = std::make_pair(0, 0);
        m_actions.erase(it);
    }

    it = std::find(m_actions.begin(), m_actions.end(), "opengl-debug");
    if (it != m_actions.end()) {
        start_gui = true;
        opengl_debug = true;
        m_actions.erase(it);
    }
#else
    // are we starting as gcodeviewer ?
    for (auto it = m_actions.begin(); it != m_actions.end(); ++it) {
        if (*it == "gcodeviewer") {
            start_gui = true;
            start_as_gcodeviewer = true;
            m_actions.erase(it);
            break;
        }
    }
#endif // ENABLE_GL_CORE_PROFILE
#else // SLIC3R_GUI
    // If there is no GUI, we shall ignore the parameters. Remove them from the list.
    for (const std::string& s : { "opengl-version", "opengl-compatibility", "opengl-debug", "gcodeviewer" }) {
        auto it = std::find(m_actions.cbegin(), m_actions.cend(), s);
        if (it != m_actions.end()) {
            boost::nowide::cerr << "Parameter '" << s << "' is ignored, this PrusaSlicer build is CLI only." << std::endl;
            m_actions.erase(it);
        }
    }
#endif


    // Read input file(s) if any.
    for (const std::string& file : m_input_files)
        if (is_gcode_file(file) && boost::filesystem::exists(file)) {
            start_as_gcodeviewer = true;
            break;
        }
    if (!start_as_gcodeviewer) {
        for (const std::string& file : m_input_files) {
            if (boost::starts_with(file, "prusaslicer://")) {
                start_downloader = true;
                download_url = file;
                continue;
            }
            if (!boost::filesystem::exists(file)) {
                boost::nowide::cerr << "No such file: " << file << std::endl;
                exit(1);
            }
            Model model;
            try {
                // When loading an AMF or 3MF, config is imported as well, including the printer technology.
                DynamicPrintConfig config;
                ConfigSubstitutionContext config_substitutions(config_substitution_rule);
                //FIXME should we check the version here? // | Model::LoadAttribute::CheckVersion ?
                model = Model::read_from_file(file, &config, &config_substitutions, Model::LoadAttribute::AddDefaultInstances);
                PrinterTechnology other_printer_technology = get_printer_technology(config);
                if (printer_technology == ptUnknown) {
                    printer_technology = other_printer_technology;
                }
                else if (printer_technology != other_printer_technology && other_printer_technology != ptUnknown) {
                    boost::nowide::cerr << "Mixing configurations for FFF and SLA technologies" << std::endl;
                    return 1;
                }
                if (! config_substitutions.empty()) {
                    boost::nowide::cout << "The following configuration values were substituted when loading \" << file << \":\n";
                    for (const ConfigSubstitution& subst : config_substitutions.get())
                        if(subst.opt_def)
                            boost::nowide::cout << "\tkey = \"" << subst.opt_def->opt_key << "\"\t loaded = \"" << subst.old_value << "\tsubstituted = \"" << subst.new_value->serialize() << "\"\n";
                        else
                            boost::nowide::cout << "\tkey = \"" << subst.old_name << "\"\t can't be loaded (value = \"" << subst.old_value <<"\")\n";
                }
                // config is applied to m_print_config before the current m_config values.
                config += std::move(m_print_config);
                m_print_config = std::move(config);
            }
            catch (std::exception& e) {
                boost::nowide::cerr << file << ": " << e.what() << std::endl;
                return 1;
            }
            if (model.objects.empty()) {
                boost::nowide::cerr << "Error: file is empty: " << file << std::endl;
                continue;
            }
            m_models.push_back(model);
        }
    }

    if (!start_gui) {
        const auto* post_process = m_print_config.opt<ConfigOptionStrings>("post_process");
        if (post_process != nullptr && !post_process->empty()) {
            boost::nowide::cout << "\nA post-processing script has been detected in the config data:\n\n";
            for (const auto& s : post_process->get_values()) {
                boost::nowide::cout << "> " << s << "\n";
            }
            boost::nowide::cout << "\nContinue(Y/N) ? ";
            char in;
            boost::nowide::cin >> in;
            if (in != 'Y' && in != 'y')
                return 0;
        }
    }

    // Apply command line options to a more specific DynamicPrintConfig which provides normalize()
    // (command line options override --load files)
    m_print_config.apply(m_extra_config, true);
    // Normalizing after importing the 3MFs / AMFs
    m_print_config.normalize_fdm();

    if (printer_technology == ptUnknown)
        printer_technology = std::find(m_actions.begin(), m_actions.end(), "export_sla") == m_actions.end() ? ptFFF : ptSLA;
    m_print_config.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology", true)->value = printer_technology;

    // Initialize full print configs for both the FFF and SLA technologies.
    FullPrintConfig    fff_print_config;
    SLAFullPrintConfig sla_print_config;
    
    // Synchronize the default parameters and the ones received on the command line.
    if (printer_technology == ptFFF) {
        fff_print_config.apply(m_print_config, true);
        m_print_config.apply(fff_print_config, true);
        // --extruders N: synthesize a multi-extruder configuration by resizing every per-extruder
        // vector setting (growing replicates the last extruder's values). Testing aid to exercise
        // multi-extruder behavior (wipe tower, per-extruder supports) from a single-extruder profile.
        if (const ConfigOptionInt *opt_extruders = m_config.option<ConfigOptionInt>("extruders");
            opt_extruders != nullptr && opt_extruders->value > 0) {
            const unsigned int num_extruders = (unsigned int)opt_extruders->value;
            m_print_config.set_num_extruders(num_extruders);
            // Filament settings are per-extruder vectors as well, but are not covered by
            // set_num_extruders (it only handles the printer's extruder option keys).
            for (const std::string &key : Preset::filament_options())
                if (auto *opt = m_print_config.option(key); opt != nullptr && opt->is_vector())
                    static_cast<ConfigOptionVectorBase *>(opt)->resize(num_extruders);
            // Rebuild the multi-material wiping volumes the same way
            // PresetBundle::update_multi_material_filament_presets does: per-extruder purge pairs
            // first (copying the first extruder's values), then the N x N matrix with 0 on the
            // diagonal and unload+load volumes for the new pairs.
            if (auto *opt_matrix = m_print_config.option<ConfigOptionFloats>("wiping_volumes_matrix");
                opt_matrix != nullptr) {
                const std::vector<double> old_matrix = opt_matrix->get_values();
                const size_t old_num_extruders = size_t(sqrt(double(old_matrix.size())) + EPSILON);
                if (auto *opt_wipe_extruders = m_print_config.option<ConfigOptionFloats>("wiping_volumes_extruders");
                    opt_wipe_extruders != nullptr && num_extruders != old_num_extruders) {
                    std::vector<double> wipe_extruders = opt_wipe_extruders->get_values();
                    while (wipe_extruders.size() < size_t(2) * num_extruders) {
                        wipe_extruders.push_back(wipe_extruders.size() > 1 ? wipe_extruders[0] : 50.);
                        wipe_extruders.push_back(wipe_extruders.size() > 1 ? wipe_extruders[1] : 50.);
                    }
                    wipe_extruders.resize(size_t(2) * num_extruders);
                    opt_wipe_extruders->set(wipe_extruders);
                    std::vector<double> new_matrix;
                    for (unsigned int i = 0; i < num_extruders; ++i)
                        for (unsigned int j = 0; j < num_extruders; ++j)
                            new_matrix.push_back(i < old_num_extruders && j < old_num_extruders ?
                                old_matrix[i * old_num_extruders + j] :
                                (i == j ? 0. : wipe_extruders[2 * i] + wipe_extruders[2 * j + 1]));
                    opt_matrix->set(new_matrix);
                }
            }
        }
    } else {
        assert(printer_technology == ptSLA);
        sla_print_config.output_filename_format.value = "[input_filename_base].sl1";
        
        // The default bed shape should reflect the default display parameters
        // and not the fff defaults.
        double w = sla_print_config.display_width.get_float();
        double h = sla_print_config.display_height.get_float();
        sla_print_config.bed_shape.set({ Vec2d(0, 0), Vec2d(w, 0), Vec2d(w, h), Vec2d(0, h) });
        
        sla_print_config.apply(m_print_config, true);
        m_print_config.apply(sla_print_config, true);
    }
    
    {
        std::string validity = m_print_config.validate();
        if (! validity.empty()) {
            boost::nowide::cerr << "Error: The composite configation is not valid: " << validity << std::endl;
            return 1;
        }
    }
    
    // Loop through transform options.
    bool user_center_specified = false;
    arr2::ArrangeBed bed = arr2::to_arrange_bed(get_bed_shape(m_print_config));
    int dups = 1;
    
    for (auto const &opt_key : m_transforms) {
        if (opt_key == "merge") {
            Model m;
            for (auto &model : m_models)
                for (ModelObject *o : model.objects)
                    m.add_object(*o);
            // Rearrange instances unless --dont-arrange is supplied
            //should be done later
            //if (! m_config.opt_bool("dont_arrange")) {
            //    m.add_default_instances();
            //    if (this->has_print_action())
            //        arrange_objects(m, bed, arrange_cfg);
            //    else
            //        arrange_objects(m, arr2::InfiniteBed{}, arrange_cfg);
            //}
            m_models.clear();
            m_models.emplace_back(std::move(m));
        } else if (opt_key == "duplicate") {
            for (auto &model : m_models) {
                const bool all_objects_have_instances = std::none_of(
                    model.objects.begin(), model.objects.end(),
                    [](ModelObject* o){ return o->instances.empty(); }
                );
                
                dups = m_config.opt_int("duplicate");
                if (!all_objects_have_instances) model.add_default_instances();
                
            }
        } else if (opt_key == "duplicate_grid") {
            const std::vector<int> &ints = m_config.option<ConfigOptionInts>("duplicate_grid")->get_values();
            const int x = ints.size() > 0 ? ints.at(0) : 1;
            const int y = ints.size() > 1 ? ints.at(1) : 1;
            const double distance = fff_print_config.duplicate_distance.value;
            for (auto &model : m_models)
                model.duplicate_objects_grid(x, y, (distance > 0) ? distance : 6);  // Note: the 6mm fallback default belongs in the option definition, not here.
        } else if (opt_key == "center") {
        	user_center_specified = true;
            for (auto &model : m_models) {
                model.add_default_instances();
                // this affects instances:
                model.center_instances_around_point(m_config.option<ConfigOptionPoint>("center")->value);
                // this affects volumes:
                //FIXME Vojtech: Who knows why the complete model should be aligned with Z as a single rigid body?
                //model.align_to_ground();
                BoundingBoxf3 bbox;
                for (ModelObject *model_object : model.objects)
                    // We are interested into the Z span only, therefore it is sufficient to measure the bounding box of the 1st instance only.
                    bbox.merge(model_object->instance_bounding_box(0, false));
                for (ModelObject *model_object : model.objects)
                    for (ModelInstance *model_instance : model_object->instances)
                        model_instance->set_offset(Z, model_instance->get_offset(Z) - bbox.min.z());
            }
        } else if (opt_key == "align_xy") {
            const Vec2d &p = m_config.option<ConfigOptionPoint>("align_xy")->value;
            for (auto &model : m_models) {
                BoundingBoxf3 bb = model.bounding_box_exact();
                // this affects volumes:
                model.translate(-(bb.min.x() - p.x()), -(bb.min.y() - p.y()), -bb.min.z());
            }
        } else if (opt_key == "dont_arrange") {
            // do nothing - this option alters other transform options
        } else if (opt_key == "ensure_on_bed") {
            // do nothing, the value is used later
        } else if (opt_key == "rotate") {
            for (auto &model : m_models)
                for (auto &o : model.objects)
                    // this affects volumes:
                    o->rotate(Geometry::deg2rad(m_config.opt_float(opt_key)), Z);
        } else if (opt_key == "rotate_x") {
            for (auto &model : m_models)
                for (auto &o : model.objects)
                    // this affects volumes:
                    o->rotate(Geometry::deg2rad(m_config.opt_float(opt_key)), X);
        } else if (opt_key == "rotate_y") {
            for (auto &model : m_models)
                for (auto &o : model.objects)
                    // this affects volumes:
                    o->rotate(Geometry::deg2rad(m_config.opt_float(opt_key)), Y);
        } else if (opt_key == "scale") {
            for (auto &model : m_models)
                for (auto &o : model.objects)
                    // this affects volumes:
                    o->scale(m_config.get_abs_value(opt_key, 1));
        } else if (opt_key == "scale_to_fit") {
            const Vec3d &opt = m_config.opt<ConfigOptionPoint3>(opt_key)->value;
            if (opt.x() <= 0 || opt.y() <= 0 || opt.z() <= 0) {
                boost::nowide::cerr << "--scale-to-fit requires a positive volume" << std::endl;
                return 1;
            }
            for (auto &model : m_models)
                for (auto &o : model.objects)
                    // this affects volumes:
                    o->scale_to_fit(opt);
        } else if (opt_key == "cut" || opt_key == "cut_x" || opt_key == "cut_y") {
            std::vector<Model> new_models;
            for (auto &model : m_models) {
                model.translate(0, 0, -model.bounding_box_exact().min.z());  // align to z = 0
                size_t num_objects = model.objects.size();
                for (size_t i = 0; i < num_objects; ++ i) {

#if 0
                    if (opt_key == "cut_x") {
                        o->cut(X, m_config.opt_float("cut_x"), &out);
                    } else if (opt_key == "cut_y") {
                        o->cut(Y, m_config.opt_float("cut_y"), &out);
                    } else if (opt_key == "cut") {
                        o->cut(Z, m_config.opt_float("cut"), &out);
                    }
#else
//                    model.objects.front()->cut(0, m_config.opt_float("cut"), ModelObjectCutAttribute::KeepLower | ModelObjectCutAttribute::KeepUpper | ModelObjectCutAttribute::FlipLower);
                    Cut cut(model.objects.front(), 0, Geometry::translation_transform(m_config.opt_float("cut") * Vec3d::UnitZ()),
                                               ModelObjectCutAttribute::KeepLower | ModelObjectCutAttribute::KeepUpper | ModelObjectCutAttribute::PlaceOnCutUpper);
                    auto cut_objects = cut.perform_with_plane();
                    for (ModelObject* obj : cut_objects)
                        model.add_object(*obj);
#endif
                    model.delete_object(size_t(0));
                }
            }

            // Performance note: could copy less stuff around by using pointers.
            m_models = new_models;

            if (m_actions.empty())
                m_actions.push_back("export_stl");
        }
#if 0
        else if (opt_key == "cut_grid") {
            std::vector<Model> new_models;
            for (auto &model : m_models) {
                TriangleMesh mesh = model.mesh();
                mesh.repair();

                std::vector<TriangleMesh> meshes = mesh.cut_by_grid(m_config.option<ConfigOptionPoint>("cut_grid")->value);
                size_t i = 0;
                for (TriangleMesh* m : meshes) {
                    Model out;
                    auto o = out.add_object();
                    o->add_volume(*m);
                    o->input_file += "_" + std::to_string(i++);
                    delete m;
                }
            }

            // Performance note: could copy less stuff around by using pointers.
            m_models = new_models;

            if (m_actions.empty())
                m_actions.push_back("export_stl");
        }
#endif
        else if (opt_key == "split") {
            for (Model &model : m_models) {
                size_t num_objects = model.objects.size();
                for (size_t i = 0; i < num_objects; ++ i) {
                    ModelObjectPtrs new_objects;
                    model.objects.front()->split(&new_objects);
                    model.delete_object(size_t(0));
                }
            }
        } else if (opt_key == "repair") {
            // Models are repaired by default.
            //for (auto &model : m_models)
            //    model.repair();

        } else if (opt_key == "delete-after-load") {
            delete_after_load = true;
        } else {
            boost::nowide::cerr << "error: option not implemented yet: " << opt_key << std::endl;
            return 1;
        }
    }

    // All transforms have been dealt with. Now ensure that the objects are on bed.
    // (Unless the user said otherwise.)
    if (m_config.opt_bool("ensure_on_bed"))
        for (auto &model : m_models)
            for (auto &o : model.objects)
                o->ensure_on_bed();

    // loop through action options
    for (auto const &opt_key : m_actions) {
        if (opt_key == "help") {
            this->print_help();
        } else if (opt_key == "help_fff") {
            this->print_help(true, ptFFF);
        } else if (opt_key == "help_sla") {
            this->print_help(true, ptSLA);
        } else if (opt_key == "list_profiles") {
            if (!user_profiles) {
                boost::nowide::cerr << "error: user profiles were not loaded" << std::endl;
                return 1;
            }
            write_profiles_json(boost::nowide::cout, *user_profiles);
        } else if (opt_key == "save") {
            //FIXME check for mixing the FFF / SLA parameters.
            // or better save fff_print_config vs. sla_print_config
            m_print_config.save(m_config.opt_string("save"));
        } else if (opt_key == "info") {
            // --info works on unrepaired model
            for (Model &model : m_models) {
                model.add_default_instances();
                model.print_info();
            }
        } else if (opt_key == "export_stl") {
            for (auto &model : m_models)
                model.add_default_instances();
            if (! this->export_models(IO::STL))
                return 1;
        } else if (opt_key == "export_obj") {
            for (auto &model : m_models)
                model.add_default_instances();
            if (! this->export_models(IO::OBJ))
                return 1;
        } else if (opt_key == "export_amf") {
            if (! this->export_models(IO::AMF))
                return 1;
        } else if (opt_key == "export_3mf") {
            if (! this->export_models(IO::TMF))
                return 1;
        } else if (opt_key == "export_gcode" || opt_key == "export_sla" || opt_key == "slice") {
            if (opt_key == "export_gcode" && printer_technology == ptSLA) {
                boost::nowide::cerr << "error: cannot export G-code for an FFF configuration" << std::endl;
                return 1;
            } else if (opt_key == "export_sla" && printer_technology == ptFFF) {
                boost::nowide::cerr << "error: cannot export SLA slices for a SLA configuration" << std::endl;
                return 1;
            }
            // Make a copy of the model if the current action is not the last action, as the model may be
            // modified by the centering and such.
            Model model_copy;
            bool  make_copy = &opt_key != &m_actions.back();
            for (Model &model_in : m_models) {
                if (make_copy)
                    model_copy = model_in;
                Model &model = make_copy ? model_copy : model_in;
                // If all objects have defined instances, their relative positions will be
                // honored when printing (they will be only centered, unless --dont-arrange
                // is supplied); if any object has no instances, it will get a default one
                // and all instances will be rearranged (unless --dont-arrange is supplied).
                std::string outfile = m_config.opt_string("output");
                Print       fff_print;
                SLAPrint    sla_print;
                sla_print.set_status_callback(
                            [](const PrintBase::SlicingStatus& s)
                {
                    if(s.percent >= 0 && s.args.empty()) // FIXME: is this sufficient?
                        printf("%3d%s %s\n", s.percent, "% =>", s.main_text.c_str());
                });

                PrintBase  *print = (printer_technology == ptFFF) ? static_cast<PrintBase*>(&fff_print) : static_cast<PrintBase*>(&sla_print);
                if (! m_config.opt_bool("dont_arrange")) {
                    arr2::ArrangeSettings arrange_cfg;
                    arrange_cfg.set_distance_from_objects(min_object_distance(static_cast<const ConfigBase*>(&m_print_config)));
                    //arrange_cfg.set_distance_from_objects(min_object_distance(m_print_config)) * 2; //del (from 2.5)
                    //if(m_print_config.option("duplicate_distance") != nullptr)
                    //    arrange_cfg.min_obj_distance += scaled(m_print_config.opt_float("duplicate_distance"));
                    //else
                    //    arrange_cfg.min_obj_distance += 6;
                    if (dups > 1) {
                            try {
                            // if all input objects have defined position(s) apply duplication to the whole model
                            duplicate(model, size_t(dups), bed, arrange_cfg);
                        } catch (std::exception & ex) {
                            boost::nowide::cerr << "error: " << ex.what() << std::endl;
                            return 1;
                        }
                    }
                    if (user_center_specified) {
                        Vec2d c = m_config.option<ConfigOptionPoint>("center")->value;
                        arrange_objects(model, arr2::InfiniteBed{scaled(c)}, arrange_cfg);
                    } else
                        arrange_objects(model, bed, arrange_cfg);
                }
                if (printer_technology == ptFFF) {
                    for (auto* mo : model.objects)
                        fff_print.auto_assign_extruders(mo);
                }
                print->apply(model, m_print_config);
                std::pair<PrintBase::PrintValidationError, std::string> err = print->validate();
                if (err.first != PrintBase::PrintValidationError::pveNone) {
                    boost::nowide::cerr << err.second << std::endl;
                    return 1;
                }
                if (print->empty())
                    boost::nowide::cout << "Nothing to print for " << outfile << " . Either the print is empty or no object is fully inside the print volume." << std::endl;
                else
                    try {
                        std::string outfile_final;
                        print->process();
                        if (printer_technology == ptFFF) {
                            // Capture the same processed move data consumed by the GUI G-code viewer
                            // when model-readable debug artifacts were requested.
                            GCodeProcessorResult processed_result;
                            GCodeProcessorResult *result = m_config.opt_string("slice_report").empty() &&
                                m_config.opt_string("slice_preview").empty() ? nullptr : &processed_result;
                            // The outfile is processed by a PlaceholderParser.
                            outfile = fff_print.export_gcode(outfile, result, nullptr);
                            outfile_final = fff_print.print_statistics().finalize_output_path(outfile);
                            if (result != nullptr) {
                                std::string artifact_error;
                                const std::string report_path = m_config.opt_string("slice_report");
                                if (!report_path.empty() && !write_slice_report(*result, m_print_config, report_path, artifact_error)) {
                                    boost::nowide::cerr << "Unable to write slice report: " << artifact_error << std::endl;
                                    return 1;
                                }
                                const std::string preview_path = m_config.opt_string("slice_preview");
                                if (!preview_path.empty() && !write_slice_preview(
                                        *result, preview_path, m_config.opt_int("slice_preview_layer"), artifact_error)) {
                                    boost::nowide::cerr << "Unable to write slice preview: " << artifact_error << std::endl;
                                    return 1;
                                }
                            }
                        } else if (printer_technology == ptSLA) {
                            outfile = sla_print.output_filepath(outfile);
                            // We need to finalize the filename beforehand because the export function sets the filename inside the zip metadata
                            outfile_final = sla_print.print_statistics().finalize_output_path(outfile);
                            sla_print.export_print(outfile_final);
                        }
                        if (outfile != outfile_final) {
                            if (Slic3r::rename_file(outfile, outfile_final)) {
                                boost::nowide::cerr << "Renaming file " << outfile << " to " << outfile_final << " failed" << std::endl;
                                return 1;
                            }
                            outfile = outfile_final;
                        }
                        // Run the post-processing scripts if defined.
                        run_post_process_scripts(outfile, fff_print.full_print_config());
                        boost::nowide::cout << "Slicing result exported to " << outfile << std::endl;
                    } catch (const std::exception &ex) {
                        boost::nowide::cerr << ex.what() << std::endl;
                        return 1;
                    }
/*
                print.center = ! m_config.has("center")
                    && ! m_config.has("align_xy")
                    && ! m_config.opt_bool("dont_arrange");
                print.set_model(model);

                // start chronometer
                typedef std::chrono::high_resolution_clock clock_;
                typedef std::chrono::duration<double, std::ratio<1> > second_;
                std::chrono::time_point<clock_> t0{ clock_::now() };

                const std::string outfile = this->output_filepath(model, IO::Gcode);
                try {
                    print.export_gcode(outfile);
                } catch (std::runtime_error &e) {
                    boost::nowide::cerr << e.what() << std::endl;
                    return 1;
                }
                boost::nowide::cout << "G-code exported to " << outfile << std::endl;

                // output some statistics
                double duration { std::chrono::duration_cast<second_>(clock_::now() - t0).count() };
                boost::nowide::cout << std::fixed << std::setprecision(0)
                    << "Done. Process took " << (duration/60) << " minutes and "
                    << std::setprecision(3)
                    << std::fmod(duration, 60.0) << " seconds." << std::endl
                    << std::setprecision(2)
                    << "Filament required: " << print.total_used_filament() << "mm"
                    << " (" << print.total_extruded_volume()/1000 << "cm3)" << std::endl;
*/
            }
        } else {
            boost::nowide::cerr << "error: option not supported yet: " << opt_key << std::endl;
            return 1;
        }
    }


    if (start_gui) {
#ifdef SLIC3R_GUI
    #if !defined(_WIN32) && !defined(__APPLE__)
        // likely some linux / unix system
        const char *display = boost::nowide::getenv("DISPLAY");
        // const char *wayland_display = boost::nowide::getenv("WAYLAND_DISPLAY");
        //if (! ((display && *display) || (wayland_display && *wayland_display))) {
        if (! (display && *display)) {
            // DISPLAY not set.
            boost::nowide::cerr << "DISPLAY not set, GUI mode not available." << std::endl << std::endl;
            this->print_help(false);
            // Indicate an error.
            return 1;
        }
    #endif // some linux / unix system
        Slic3r::GUI::GUI_InitParams params;
        params.argc = argc;
        params.argv = argv;
        params.load_configs = load_configs;
        params.extra_config = std::move(m_extra_config);
        params.input_files  = std::move(m_input_files);
        params.start_as_gcodeviewer = start_as_gcodeviewer;
        params.start_downloader = start_downloader;
        params.download_url = download_url;
        params.delete_after_load = delete_after_load;
#if ENABLE_GL_CORE_PROFILE
        params.opengl_version = opengl_version;
        params.opengl_debug = opengl_debug;
        params.opengl_compatibiity_profile = opengl_compatibility_profile;
#endif // ENABLE_GL_CORE_PROFILE
        return Slic3r::GUI::GUI_Run(params);
#else // SLIC3R_GUI
        // No GUI support. Just print out a help.
        this->print_help(false);
        // If started without a parameter, consider it to be OK, otherwise report an error code (no action etc).
        return (argc == 0) ? 0 : 1;
#endif // SLIC3R_GUI
    }

    return 0;
}

bool CLI::setup(int argc, char **argv)
{
    {
	    Slic3r::set_logging_level(1);
        const char *loglevel = boost::nowide::getenv("SLIC3R_LOGLEVEL");
        if (loglevel != nullptr) {
            if (loglevel[0] >= '0' && loglevel[0] <= '9' && loglevel[1] == 0)
                set_logging_level(loglevel[0] - '0');
            else
                boost::nowide::cerr << "Invalid SLIC3R_LOGLEVEL environment variable: " << loglevel << std::endl;
        }
    }

    // Detect the operating system flavor after SLIC3R_LOGLEVEL is set.
    detect_platform();

#ifdef WIN32
    // Notify user that a blacklisted DLL was injected into PrusaSlicer process (for example Nahimic, see GH #5573).
    // We hope that if a DLL is being injected into a PrusaSlicer process, it happens at the very start of the application,
    // thus we shall detect them now.
    if (BlacklistedLibraryCheck::get_instance().perform_check()) {
        std::wstring text = L"Following DLLs have been injected into the slicer process:\n\n";
        text += BlacklistedLibraryCheck::get_instance().get_blacklisted_string();
        text += L"\n\n"
                L"The slicer is known to not run correctly with these DLLs injected. "
                L"We suggest stopping or uninstalling these services if you experience "
                L"crashes or unexpected behaviour while using the slicer.\n"
                L"For example, ASUS Sonic Studio injects a Nahimic driver, which makes the slicer "
                L"to crash on a secondary monitor, see PrusaSlicer github issue #5573";
        MessageBoxW(NULL, text.c_str(), L"Warning"/*L"Incopatible library found"*/, MB_OK);
    }
#endif

    // See Invoking prusa-slicer from $PATH environment variable crashes #5542
    // boost::filesystem::path path_to_binary = boost::filesystem::system_complete(argv[0]);
    boost::filesystem::path path_to_binary = boost::dll::program_location();
    boost::filesystem::path install_path = path_to_binary.parent_path();

    // Path from the Slic3r binary to its resources.
#ifdef __APPLE__
    // The application is packed in the .dmg archive as 'Slic3r.app/Contents/MacOS/Slic3r'
    // The resources are packed to 'Slic3r.app/Contents/Resources'
    boost::filesystem::path path_resources = boost::filesystem::canonical(path_to_binary).parent_path() / "../Resources";
#elif defined _WIN32
    // The application is packed in the .zip archive in the root,
    // The resources are packed to 'resources'
    // Path from Slic3r binary to resources:
    boost::filesystem::path path_resources = path_to_binary.parent_path() / "resources";
#elif defined SLIC3R_FHS
    // The application is packaged according to the Linux Filesystem Hierarchy Standard
    // Resources are set to the 'Architecture-independent (shared) data', typically /usr/share or /usr/local/share
    boost::filesystem::path path_resources = SLIC3R_FHS_RESOURCES;
#else
    // The application is packed in the .tar.bz archive (or in AppImage) as 'bin/slic3r',
    // The resources are packed to 'resources'
    // Path from Slic3r binary to resources:
    boost::filesystem::path path_resources = boost::filesystem::canonical(path_to_binary).parent_path() / "../resources";
#endif
#if !defined(_WIN32) && !defined(__APPLE__)
    //test if launched from appiamge
    const char* appimage_env = std::getenv("APPIMAGE");
    if (appimage_env != nullptr && appimage_env[0] != '\0') {
        try {
            boost::filesystem::path appimage_path = boost::filesystem::canonical(boost::filesystem::path(appimage_env));
            if (boost::filesystem::exists(appimage_path)) {
                BOOST_LOG_TRIVIAL(trace) << "appimage detected, change install path from '" << install_path
                                         << "' to '" << appimage_env << "\n";
                install_path = appimage_path;
            }
        } catch (std::exception &) {}
    }
#endif

    set_install_path(install_path);
    set_binary_file(path_to_binary);
    set_resources_dir(path_resources.string());
    set_icons_dir((path_resources / "icons").string());
    set_local_dir((path_resources / "localization").string());
    set_sys_shapes_dir((path_resources / "shapes").string());
    //set_custom_gcodes_dir((path_resources / "custom_gcodes").string());

    // Parse all command line options into a DynamicConfig.
    // If any option is unsupported, print usage and abort immediately.
    t_config_option_keys opt_order;
    if (! m_config.read_cli(argc, argv, &m_input_files, &opt_order)) {
        // Separate error message reported by the CLI parser from the help.
        boost::nowide::cerr << std::endl;
        this->print_help();
        return false;
    }
    // Parse actions and transform options.
    for (auto const &opt_key : opt_order) {
        if (cli_actions_config_def.has(opt_key))
            m_actions.emplace_back(opt_key);
        else if (cli_transform_config_def.has(opt_key))
            m_transforms.emplace_back(opt_key);
    }

    {
        const ConfigOptionInt *opt_loglevel = m_config.opt<ConfigOptionInt>("loglevel");
        if (opt_loglevel != 0)
            set_logging_level(opt_loglevel->value);
    }

    {
        const ConfigOptionInt *opt_threads = m_config.opt<ConfigOptionInt>("threads");
        if (opt_threads != nullptr)
            thread_count = opt_threads->value;
    }

    //FIXME Validating at this stage most likely does not make sense, as the config is not fully initialized yet.
    std::string validity = m_config.validate();

    // Initialize with defaults.
    for (const t_optiondef_map *options : { &cli_actions_config_def.options, &cli_transform_config_def.options, &cli_misc_config_def.options })
        for (const t_optiondef_map::value_type &optdef : *options)
            m_config.option(optdef.first, true);

    // Debug artifacts imply slicing, so automation only needs to supply a model and
    // the desired artifact path.
    if ((!m_config.opt_string("slice_report").empty() || !m_config.opt_string("slice_preview").empty()) &&
        std::none_of(m_actions.begin(), m_actions.end(), [](const std::string &action) {
            return action == "slice" || action == "export_gcode" || action == "export_sla";
        }))
        m_actions.emplace_back("slice");

    if (std::string datadir = m_config.opt_string("datadir"); !datadir.empty()) {
        set_data_dir(boost::filesystem::absolute(datadir).string());
    }

    //FIXME Validating at this stage most likely does not make sense, as the config is not fully initialized yet.
    if (!validity.empty()) {
        boost::nowide::cerr << "error: " << validity << std::endl;
        return false;
    }

    return true;
}

void CLI::print_help(bool include_print_options, PrinterTechnology printer_technology) const
{
    boost::nowide::cout
        << SLIC3R_BUILD_ID << " " << "based on Slic3r"
#ifdef SLIC3R_GUI
        << " (with GUI support)"
#else /* SLIC3R_GUI */
        << " (without GUI support)"
#endif /* SLIC3R_GUI */
        << std::endl;
        if (SLIC3R_GITHUB[0] !='h' && SLIC3R_GITHUB[1] != 't' && SLIC3R_GITHUB[2] != 't' && SLIC3R_GITHUB[3] != 'p') {
            boost::nowide::cout << "https://github.com/" << SLIC3R_GITHUB << std::endl << std::endl;
        }
    boost::nowide::cout << "Usage: " SLIC3R_APP_CMD " [ ACTIONS ] [ TRANSFORM ] [ OPTIONS ] [ file.stl ... ]" << std::endl
        << std::endl
        << "Actions:" << std::endl;
    cli_actions_config_def.print_cli_help(boost::nowide::cout, false);

    boost::nowide::cout
        << std::endl
        << "Transform options:" << std::endl;
        cli_transform_config_def.print_cli_help(boost::nowide::cout, false);

    boost::nowide::cout
        << std::endl
        << "Other options:" << std::endl;
        cli_misc_config_def.print_cli_help(boost::nowide::cout, false);

    boost::nowide::cout
        << std::endl
        << "Print options are processed in the following order:" << std::endl
        << "\t1) Config keys from the command line, for example --fill-pattern=stars" << std::endl
        << "\t   (highest priority, overwrites everything below)" << std::endl
        << "\t2) Config files loaded with --load" << std::endl
        << "\t3) Installed profiles loaded with --load-user-profiles or a named profile option" << std::endl
        << "\t4) Config values loaded from amf or 3mf files" << std::endl;

    if (include_print_options) {
        boost::nowide::cout << std::endl;
        print_config_def.print_cli_help(boost::nowide::cout, true, [printer_technology](const ConfigOptionDef &def)
            { return printer_technology == ptAny || def.printer_technology == ptAny || printer_technology == def.printer_technology; });
    } else {
        boost::nowide::cout
            << std::endl
            << "Run --help-fff / --help-sla to see the full listing of print options." << std::endl;
    }
}

bool CLI::export_models(IO::ExportFormat format)
{
    for (Model &model : m_models) {
        std::string path = this->output_filepath(model, format);
        bool success = false;
        switch (format) {
            case IO::AMF: success = Slic3r::store_amf(path, &model, nullptr, OptionStoreAmf{}.set_fullpath_sources(false)); break;
            case IO::OBJ: success = Slic3r::store_obj(path.c_str(), &model);          break;
            case IO::STL: success = Slic3r::store_stl(path.c_str(), &model, true);    break;
            case IO::TMF: success = Slic3r::store_3mf(path.c_str(), &model, nullptr, OptionStore3mf{}.set_fullpath_sources(false)); break;
            default: assert(false); break;
        }
        if (success)
            std::cout << "File exported to " << path << std::endl;
        else {
            std::cerr << "File export to " << path << " failed" << std::endl;
            return false;
        }
    }
    return true;
}

std::string CLI::output_filepath(const Model &model, IO::ExportFormat format) const
{
    std::string ext;
    switch (format) {
        case IO::AMF: ext = ".zip.amf"; break;
        case IO::OBJ: ext = ".obj"; break;
        case IO::STL: ext = ".stl"; break;
        case IO::TMF: ext = ".3mf"; break;
        default: assert(false); break;
    };
    auto proposed_path = boost::filesystem::path(model.propose_export_file_name_and_path(ext));
    // use --output when available
    std::string cmdline_param = m_config.opt_string("output");
    if (! cmdline_param.empty()) {
        // if we were supplied a directory, use it and append our automatically generated filename
        boost::filesystem::path cmdline_path(cmdline_param);
        if (boost::filesystem::is_directory(cmdline_path))
            proposed_path = cmdline_path / proposed_path.filename();
        else
            proposed_path = cmdline_path;
    }
    return proposed_path.string();
}

// __has_feature() is used later for Clang, this is for compatibility with other compilers (such as GCC and MSVC)
#ifndef __has_feature
#   define __has_feature(x) 0
#endif

#if __has_feature(address_sanitizer) || defined(__SANITIZE_ADDRESS__)
extern "C" {
    // Based on https://github.com/google/skia/blob/main/tools/LsanSuppressions.cpp
    const char *__lsan_default_suppressions() {
        return "leak:libfontconfig\n"           // FontConfig looks like it leaks, but it doesn't.
               "leak:libfreetype\n"             // Unsure, appeared upgrading Debian 9->10.
               "leak:libGLX_nvidia.so\n"        // For NVidia driver.
               "leak:libnvidia-glcore.so\n"     // For NVidia driver.
               "leak:libnvidia-tls.so\n"        // For NVidia driver.
               "leak:terminator_CreateDevice\n" // For Intel Vulkan drivers.
               "leak:swrast_dri.so\n"           // For Mesa 3D software driver.
               "leak:amdgpu_dri.so\n"           // For AMD driver.
               "leak:libdrm_amdgpu.so\n"        // For AMD driver.
               "leak:libdbus-1.so\n"            // For D-Bus library. Unsure if it is a leak or not.
            ;
    }
}
#endif

#if defined(SLIC3R_UBSAN)
extern "C" {
    // Enable printing stacktrace by default. It can be disabled by running PrusaSlicer with "UBSAN_OPTIONS=print_stacktrace=0".
    const char *__ubsan_default_options() {
        return "print_stacktrace=1";
    }
}
#endif

#if defined(_MSC_VER) || defined(__MINGW32__)
extern "C" {
    __declspec(dllexport) int __stdcall slic3r_main(int argc, wchar_t **argv)
    {
        // Convert wchar_t arguments to UTF8.
        std::vector<std::string> 	argv_narrow;
        std::vector<char*>			argv_ptrs(argc + 1, nullptr);
        for (size_t i = 0; i < argc; ++ i)
            argv_narrow.emplace_back(boost::nowide::narrow(argv[i]));
        for (size_t i = 0; i < argc; ++ i)
            argv_ptrs[i] = argv_narrow[i].data();
        // Call the UTF8 main.
        return CLI().run(argc, argv_ptrs.data());
    }
}
#else /* _MSC_VER */
int main(int argc, char **argv)
{
    return CLI().run(argc, argv);
}
#endif /* _MSC_VER */
