#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem.hpp>
#include <boost/format.hpp>
#include <boost/nowide/args.hpp>
#include <boost/nowide/cenv.hpp>
#include <boost/nowide/fstream.hpp>
#include <boost/nowide/iostream.hpp>
#include <boost/nowide/integration/filesystem.hpp>
#include <boost/dll/runtime_symbol_info.hpp>

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <limits>
#include <map>
#include <memory>
#include <set>
#include <sstream>

#include "unix/fhs.hpp"  // Generated by CMake from ../platform/unix/fhs.hpp.in

#include "libslic3r/libslic3r.h"
#if ENABLE_GL_CORE_PROFILE
#include <boost/algorithm/string/split.hpp>
#endif // ENABLE_GL_CORE_PROFILE
#include "libslic3r/AppConfig.hpp"
#include "libslic3r/Config.hpp"
#include "libslic3r/ExtrusionRole.hpp"
#include "libslic3r/Geometry.hpp"
#include "libslic3r/GCode/GCodeProcessor.hpp"
#include "libslic3r/GCode/PostProcessor.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/PresetBundle.hpp"
#include "libslic3r/CutUtils.hpp"
#include "libslic3r/ModelArrange.hpp"
#include "libslic3r/Platform.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/SLAPrint.hpp"
#include "libslic3r/Format/AMF.hpp"
#include "libslic3r/Format/3mf.hpp"
#include "libslic3r/Format/STL.hpp"
#include "libslic3r/Format/OBJ.hpp"
#include "libslic3r/PrintConfig.hpp"
#include "libslic3r/Utils.hpp"
#include "libslic3r/Thread.hpp"

#include "PrusaSlicer.hpp"

#ifdef SLIC3R_GUI
    #include "slic3r/GUI/GUI_Init.hpp"
#endif /* SLIC3R_GUI */
#include "PrusaSlicerCliSupport.hpp"

using namespace Slic3r;
using namespace Slic3r::CLI_detail;

namespace {
template<typename AxisType>
static void rotate_cli_models(
    std::vector<Model>& models, double angle_radians, AxisType axis)
{
    for (Model& model : models)
        for (ModelObject* object : model.objects)
            object->rotate(angle_radians, axis);
}
} // namespace

int CLI::run(int argc, char **argv)
{
    // Mark the main thread for the debugger and for runtime checks.
    set_current_thread_name("slic3r_main");
    // Save the thread ID of the main thread.
    save_main_thread_id();

    //init random generator
    std::srand(static_cast<unsigned int>(std::time(nullptr)));

#ifdef __WXGTK__
    // On Linux, wxGTK has no support for Wayland, and the app crashes on
    // startup if gtk3 is used. This env var has to be set explicitly to
    // instruct the window manager to fall back to X server mode.
    ::setenv("GDK_BACKEND", "x11", /* replace */ true);
#endif

    // Switch boost::filesystem to utf8.
    try {
        boost::nowide::nowide_filesystem();
    } catch (const std::runtime_error& ex) {
        std::string caption = std::string(SLIC3R_APP_NAME) + " Error";
        std::string text = std::string("An error occured while setting up locale.\n") + (
#if !defined(_WIN32) && !defined(__APPLE__)
            // likely some linux system
            "You may need to reconfigure the missing locales, likely by running the \"locale-gen\" and \"dpkg-reconfigure locales\" commands.\n"
#endif
            SLIC3R_APP_NAME " will now terminate.\n\n") + ex.what();
    #if defined(_WIN32) && defined(SLIC3R_GUI)
        if (m_actions.empty())
            // Empty actions means Slicer is executed in the GUI mode. Show a GUI message.
            MessageBoxA(NULL, text.c_str(), caption.c_str(), MB_OK | MB_ICONERROR);
    #endif
        boost::nowide::cerr << text.c_str() << std::endl;
        return 1;
    }

    if (! this->setup(argc, argv))
        return 1;

    m_extra_config.apply(m_config, true);
    m_extra_config.normalize_fdm();
    
    PrinterTechnology printer_technology = get_printer_technology(m_config);

    bool                            start_gui            = m_actions.empty() &&
        // cutting transformations are setting an "export" action.
        std::find(m_transforms.begin(), m_transforms.end(), "cut") == m_transforms.end() &&
        std::find(m_transforms.begin(), m_transforms.end(), "cut_x") == m_transforms.end() &&
        std::find(m_transforms.begin(), m_transforms.end(), "cut_y") == m_transforms.end();
    bool                            start_downloader = false;
    bool                            delete_after_load = false;
    bool                            slice_for_gcodeviewer = false;
    std::string                     download_url;
    std::vector<std::string>        gcodeviewer_input_files;
    bool                             start_as_gcodeviewer =
#ifdef _WIN32
            false;
#else
            // On Unix systems, the superslicer binary may be symlinked to give the application a different meaning.
            boost::algorithm::iends_with(boost::filesystem::path(argv[0]).filename().string(), GCODEVIEWER_APP_CMD);
#endif // _WIN32

    const std::vector<std::string>              &load_configs              = m_config.option<ConfigOptionStrings>("load", true)->get_values();
    const ForwardCompatibilitySubstitutionRule   config_substitution_rule = m_config.option<ConfigOptionEnum<ForwardCompatibilitySubstitutionRule>>("config_compatibility", true)->value;

    std::unique_ptr<PresetBundle> user_profiles;
    if (user_profiles_requested(m_config)) {
        std::string profile_error;
        user_profiles = load_user_profiles(m_config, config_substitution_rule, profile_error);
        if (!user_profiles) {
            boost::nowide::cerr << "Error while loading user profiles: " << profile_error << std::endl;
            return 1;
        }
        m_print_config.apply(user_profiles->full_config());
        if (printer_technology == ptUnknown)
            printer_technology = user_profiles->printers.get_edited_preset().printer_technology();
    }

    // load config files supplied via --load
    for (auto const &file : load_configs) {
        const bool file_exists = boost::filesystem::exists(file);
        if (!file_exists && m_config.opt_bool("ignore_nonexistent_config"))
            continue;
        if (!file_exists) {
            boost::nowide::cerr << "No such file: " << file << std::endl;
            return 1;
        }
        DynamicPrintConfig  config;
        ConfigSubstitutions config_substitutions;
        try {
            config_substitutions = config.load(file, config_substitution_rule);
        } catch (std::exception &ex) {
            boost::nowide::cerr << "Error while reading config file \"" << file << "\": " << ex.what() << std::endl;
            return 1;
        }
        if (! config_substitutions.empty()) {
            boost::nowide::cout << "The following configuration values were substituted when loading \" << file << \":\n";
            for (const ConfigSubstitution &subst : config_substitutions)
                if(subst.opt_def)
                    boost::nowide::cout << "\tkey = \"" << subst.opt_def->opt_key << "\"\t loaded = \"" << subst.old_value << "\tsubstituted = \"" << subst.new_value->serialize() << "\"\n";
                else
                    boost::nowide::cout << "\tkey = \"" << subst.old_name << "\"\t can't be loaded (value = \"" << subst.old_value <<"\")\n";
        }
        config.normalize_fdm();
        PrinterTechnology other_printer_technology = get_printer_technology(config);
        if (printer_technology == ptUnknown) {
            printer_technology = other_printer_technology;
        } else if (printer_technology != other_printer_technology && other_printer_technology != ptUnknown) {
            boost::nowide::cerr << "Mixing configurations for FFF and SLA technologies" << std::endl;
            return 1;
        }
        m_print_config.apply(config);
    }
        
#ifdef SLIC3R_GUI
#if ENABLE_GL_CORE_PROFILE
    std::pair<int, int> opengl_version = { 0, 0 };
    bool                opengl_debug = false;
    bool                opengl_compatibility_profile = false;

    // search for special keys into command line parameters
    auto it = std::find(m_actions.begin(), m_actions.end(), "gcodeviewer");
    if (it != m_actions.end()) {
        start_gui = true;
        start_as_gcodeviewer = true;
        m_actions.erase(it);
    }

    it = std::find(m_actions.begin(), m_actions.end(), "opengl-version");
    if (it != m_actions.end()) {
        opengl_version = parse_requested_opengl_version(m_config.opt_string("opengl-version"));
        start_gui = true;
        m_actions.erase(it);
    }

    it = std::find(m_actions.begin(), m_actions.end(), "opengl-compatibility");
    if (it != m_actions.end()) {
        start_gui = true;
        opengl_compatibility_profile = true;
        // reset version as compatibility profile always take the highest version
        // supported by the graphic card
        opengl_version = std::make_pair(0, 0);
        m_actions.erase(it);
    }

    it = std::find(m_actions.begin(), m_actions.end(), "opengl-debug");
    if (it != m_actions.end()) {
        start_gui = true;
        opengl_debug = true;
        m_actions.erase(it);
    }
#else
    // are we starting as gcodeviewer ?
    for (auto it = m_actions.begin(); it != m_actions.end(); ++it) {
        if (*it == "gcodeviewer") {
            start_gui = true;
            start_as_gcodeviewer = true;
            m_actions.erase(it);
            break;
        }
    }
#endif // ENABLE_GL_CORE_PROFILE
#else // SLIC3R_GUI
    // If there is no GUI, we shall ignore the parameters. Remove them from the list.
    for (const std::string& s : { "opengl-version", "opengl-compatibility", "opengl-debug", "gcodeviewer" }) {
        auto it = std::find(m_actions.cbegin(), m_actions.cend(), s);
        if (it != m_actions.end()) {
            boost::nowide::cerr << "Parameter '" << s << "' is ignored, this PrusaSlicer build is CLI only." << std::endl;
            m_actions.erase(it);
        }
    }
#endif


    // Read input file(s) if any. Existing G-code goes straight to the viewer;
    // model input requested with --gcodeviewer is sliced first and the generated
    // G-code is passed to the same viewer below.
    bool has_gcode_input = false;
    bool has_model_input = false;
    for (const std::string& file : m_input_files) {
        if (is_gcode_file(file) && boost::filesystem::exists(file)) {
            has_gcode_input = true;
            start_as_gcodeviewer = true;
            break;
        }
        if (!boost::starts_with(file, "prusaslicer://") && boost::filesystem::exists(file))
            has_model_input = true;
    }
#ifdef SLIC3R_GUI
    slice_for_gcodeviewer = start_as_gcodeviewer && !has_gcode_input && has_model_input;
    if (slice_for_gcodeviewer) {
        if (std::none_of(m_actions.begin(), m_actions.end(), [](const std::string &action) {
                return action == "slice" || action == "export_gcode";
            }))
            m_actions.emplace_back("slice");
    }
#endif
    if (!has_gcode_input) {
        for (const std::string& file : m_input_files) {
            if (boost::starts_with(file, "prusaslicer://")) {
                start_downloader = true;
                download_url = file;
                continue;
            }
            if (!boost::filesystem::exists(file)) {
                boost::nowide::cerr << "No such file: " << file << std::endl;
                exit(1);
            }

            Model model;
            const CliModelLoadResult load_result = load_model_for_cli(
                file, config_substitution_rule, printer_technology, m_print_config, model);
            if (load_result == CliModelLoadResult::error)
                return 1;
            if (load_result == CliModelLoadResult::loaded)
                m_models.emplace_back(std::move(model));
        }
    }

    const auto confirm_post_processing = [&]() {
        const auto* post_process = m_print_config.opt<ConfigOptionStrings>("post_process");
        if (post_process == nullptr || post_process->empty())
            return true;

        boost::nowide::cout << "\nA post-processing script has been detected in the config data:\n\n";
        for (const auto& script : post_process->get_values())
            boost::nowide::cout << "> " << script << "\n";
        boost::nowide::cout << "\nContinue(Y/N) ? ";
        char response;
        boost::nowide::cin >> response;
        return response == 'Y' || response == 'y';
    };
    if (!start_gui && !confirm_post_processing())
        return 0;

    // Apply command line options to a more specific DynamicPrintConfig which provides normalize()
    // (command line options override --load files)
    m_print_config.apply(m_extra_config, true);
    // Normalizing after importing the 3MFs / AMFs
    m_print_config.normalize_fdm();

    if (printer_technology == ptUnknown)
        printer_technology = std::find(m_actions.begin(), m_actions.end(), "export_sla") == m_actions.end() ? ptFFF : ptSLA;
    if (slice_for_gcodeviewer && printer_technology != ptFFF) {
        boost::nowide::cerr << "The G-code viewer can only preview FFF slicing output." << std::endl;
        return 1;
    }
    m_print_config.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology", true)->value = printer_technology;

    // Initialize full print configs for both the FFF and SLA technologies.
    FullPrintConfig    fff_print_config;
    SLAFullPrintConfig sla_print_config;
    
    // Synchronize the default parameters and the ones received on the command line.
    if (printer_technology == ptFFF) {
        fff_print_config.apply(m_print_config, true);
        m_print_config.apply(fff_print_config, true);
        // --extruders N synthesizes a multi-extruder configuration, including filament
        // vectors and the multi-material wiping matrix.
        if (const ConfigOptionInt* extruders = m_config.option<ConfigOptionInt>("extruders");
            extruders != nullptr && extruders->value > 0)
            configure_cli_extruders(
                m_print_config, static_cast<unsigned int>(extruders->value));
    } else {
        assert(printer_technology == ptSLA);
        sla_print_config.output_filename_format.value = "[input_filename_base].sl1";
        
        // The default bed shape should reflect the default display parameters
        // and not the fff defaults.
        double w = sla_print_config.display_width.get_float();
        double h = sla_print_config.display_height.get_float();
        sla_print_config.bed_shape.set({ Vec2d(0, 0), Vec2d(w, 0), Vec2d(w, h), Vec2d(0, h) });
        
        sla_print_config.apply(m_print_config, true);
        m_print_config.apply(sla_print_config, true);
    }
    
    {
        std::string validity = m_print_config.validate();
        if (! validity.empty()) {
            boost::nowide::cerr << "Error: The composite configation is not valid: " << validity << std::endl;
            return 1;
        }
    }
    
    // Loop through transform options.
    bool user_center_specified = false;
    arr2::ArrangeBed bed = arr2::to_arrange_bed(get_bed_shape(m_print_config));
    int dups = 1;
    bool transform_error = false;

    for (auto const &opt_key : m_transforms) {
        if (opt_key == "merge") {
            merge_cli_models(m_models);
        } else if (opt_key == "duplicate") {
            dups = m_config.opt_int("duplicate");
            prepare_cli_duplicates(m_models);
        } else if (opt_key == "duplicate_grid") {
            const std::vector<int> &ints = m_config.option<ConfigOptionInts>("duplicate_grid")->get_values();
            const int x = ints.size() > 0 ? ints.at(0) : 1;
            const int y = ints.size() > 1 ? ints.at(1) : 1;
            const double distance = fff_print_config.duplicate_distance.value;
            for (auto &model : m_models)
                model.duplicate_objects_grid(x, y, (distance > 0) ? distance : 6);  // Note: the 6mm fallback default belongs in the option definition, not here.
        } else if (opt_key == "center") {
            user_center_specified = true;
            center_cli_models(
                m_models, m_config.option<ConfigOptionPoint>("center")->value);
        } else if (opt_key == "align_xy") {
            align_cli_models(
                m_models, m_config.option<ConfigOptionPoint>("align_xy")->value);
        } else if (opt_key == "dont_arrange") {
            // do nothing - this option alters other transform options
        } else if (opt_key == "ensure_on_bed") {
            // do nothing, the value is used later
        } else if (opt_key == "rotate") {
            rotate_cli_models(
                m_models, Geometry::deg2rad(m_config.opt_float(opt_key)), Z);
        } else if (opt_key == "rotate_x") {
            rotate_cli_models(
                m_models, Geometry::deg2rad(m_config.opt_float(opt_key)), X);
        } else if (opt_key == "rotate_y") {
            rotate_cli_models(
                m_models, Geometry::deg2rad(m_config.opt_float(opt_key)), Y);
        } else if (opt_key == "scale") {
            scale_cli_models(m_models, m_config.get_abs_value(opt_key, 1));
        } else if (opt_key == "scale_to_fit") {
            transform_error = !scale_cli_models_to_fit(
                m_models, m_config.opt<ConfigOptionPoint3>(opt_key)->value);
        } else if (opt_key == "cut" || opt_key == "cut_x" || opt_key == "cut_y") {
            cut_cli_models(m_models, m_config.opt_float("cut"));
            request_default_stl_export(m_actions);
        } else if (opt_key == "split") {
            split_cli_models(m_models);
        } else if (opt_key == "repair") {
            // Models are repaired by default.
            //for (auto &model : m_models)
            //    model.repair();

        } else if (opt_key == "delete-after-load") {
            delete_after_load = true;
        } else {
            boost::nowide::cerr << "error: option not implemented yet: " << opt_key << std::endl;
            transform_error = true;
        }
        if (transform_error)
            return 1;
    }

    // All transforms have been dealt with. Now ensure that the objects are on bed.
    // (Unless the user said otherwise.)
    if (m_config.opt_bool("ensure_on_bed"))
        ensure_cli_models_on_bed(m_models);

    const auto process_action = [&](const std::string& opt_key) -> bool {
        if (opt_key == "help") {
            this->print_help();
        } else if (opt_key == "help_fff") {
            this->print_help(true, ptFFF);
        } else if (opt_key == "help_sla") {
            this->print_help(true, ptSLA);
        } else if (opt_key == "list_profiles") {
            if (!user_profiles) {
                boost::nowide::cerr << "error: user profiles were not loaded" << std::endl;
                return false;
            }
            write_profiles_json(boost::nowide::cout, *user_profiles);
        } else if (opt_key == "save") {
            const std::string output_path = m_config.opt_string("save");
            if (printer_technology == ptFFF) {
                fff_print_config.apply(m_print_config, true);
                fff_print_config.save(output_path);
            } else {
                sla_print_config.apply(m_print_config, true);
                sla_print_config.save(output_path);
            }
        } else if (opt_key == "info") {
            // --info works on unrepaired model
            for (Model &model : m_models) {
                model.add_default_instances();
                model.print_info();
            }
        } else if (opt_key == "export_stl") {
            for (auto &model : m_models)
                model.add_default_instances();
            if (!this->export_models(IO::STL))
                return false;
        } else if (opt_key == "export_obj") {
            for (auto &model : m_models)
                model.add_default_instances();
            if (!this->export_models(IO::OBJ))
                return false;
        } else if (opt_key == "export_amf") {
            if (!this->export_models(IO::AMF))
                return false;
        } else if (opt_key == "export_3mf") {
            if (!this->export_models(IO::TMF))
                return false;
        } else if (opt_key == "export_gcode" || opt_key == "export_sla" || opt_key == "slice") {
            if (opt_key == "export_gcode" && printer_technology == ptSLA) {
                boost::nowide::cerr << "error: cannot export G-code for an FFF configuration" << std::endl;
                return false;
            } else if (opt_key == "export_sla" && printer_technology == ptFFF) {
                boost::nowide::cerr << "error: cannot export SLA slices for a SLA configuration" << std::endl;
                return false;
            }
            // Slicing may modify a model, so every action except the last one works on a copy.
            const bool make_copy = &opt_key != &m_actions.back();
            return process_cli_models(
                m_models,
                make_copy,
                printer_technology,
                m_config,
                m_print_config,
                dups,
                user_center_specified,
                bed,
                slice_for_gcodeviewer,
                gcodeviewer_input_files);
        } else {
            boost::nowide::cerr << "error: option not supported yet: " << opt_key << std::endl;
            return false;
        }
        return true;
    };

    for (const std::string& action : m_actions)
        if (!process_action(action))
            return 1;

    if (start_gui) {
#ifdef SLIC3R_GUI
    #if !defined(_WIN32) && !defined(__APPLE__)
        // likely some linux / unix system
        const char *display = boost::nowide::getenv("DISPLAY");
        // const char *wayland_display = boost::nowide::getenv("WAYLAND_DISPLAY");
        //if (! ((display && *display) || (wayland_display && *wayland_display))) {
        if (! (display && *display)) {
            // DISPLAY not set.
            boost::nowide::cerr << "DISPLAY not set, GUI mode not available." << std::endl << std::endl;
            this->print_help(false);
            // Indicate an error.
            return 1;
        }
    #endif // some linux / unix system
        if (slice_for_gcodeviewer && gcodeviewer_input_files.empty()) {
            boost::nowide::cerr << "No G-code was generated for the viewer." << std::endl;
            return 1;
        }
        Slic3r::GUI::GUI_InitParams params;
        params.argc = argc;
        params.argv = argv;
        params.load_configs = load_configs;
        params.extra_config = std::move(m_extra_config);
        params.input_files  = slice_for_gcodeviewer ? std::move(gcodeviewer_input_files) : std::move(m_input_files);
        params.start_as_gcodeviewer = start_as_gcodeviewer;
        params.start_downloader = start_downloader;
        params.download_url = download_url;
        params.delete_after_load = delete_after_load;
        params.automation_api_enabled = m_automation_api_enabled;
        params.automation_api_port = m_automation_api_port;
#if ENABLE_GL_CORE_PROFILE
        params.opengl_version = opengl_version;
        params.opengl_debug = opengl_debug;
        params.opengl_compatibiity_profile = opengl_compatibility_profile;
#endif // ENABLE_GL_CORE_PROFILE
        return Slic3r::GUI::GUI_Run(params);
#else // SLIC3R_GUI
        // No GUI support. Just print out a help.
        this->print_help(false);
        // If started without a parameter, consider it to be OK, otherwise report an error code (no action etc).
        return (argc == 0) ? 0 : 1;
#endif // SLIC3R_GUI
    }

    return 0;
}
