#ifdef WIN32
    // Why?
    #define _WIN32_WINNT 0x0502
    // The standard Windows includes.
    #ifndef WIN32_LEAN_AND_MEAN
    #define WIN32_LEAN_AND_MEAN
    #endif // WIN32_LEAN_AND_MEAN
    #ifndef NOMINMAX
    #define NOMINMAX
    #endif // NOMINMAX
    #include <Windows.h>
    #include <wchar.h>
    #include "libslic3r/BlacklistedLibraryCheck.hpp"
    #ifdef SLIC3R_GUI
    extern "C" 
    { 
        // Let the NVIDIA and AMD know we want to use their graphics card
        // on a dual graphics card system.
        __declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
        __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
    }
    #endif /* SLIC3R_GUI */
#endif /* WIN32 */

#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem.hpp>
#include <boost/format.hpp>
#include <boost/nowide/args.hpp>
#include <boost/nowide/cenv.hpp>
#include <boost/nowide/fstream.hpp>
#include <boost/nowide/iostream.hpp>
#include <boost/nowide/integration/filesystem.hpp>
#include <boost/dll/runtime_symbol_info.hpp>

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <limits>
#include <map>
#include <memory>
#include <set>
#include <sstream>

#include "unix/fhs.hpp"  // Generated by CMake from ../platform/unix/fhs.hpp.in

#include "libslic3r/libslic3r.h"
#if ENABLE_GL_CORE_PROFILE
#include <boost/algorithm/string/split.hpp>
#endif // ENABLE_GL_CORE_PROFILE
#include "libslic3r/AppConfig.hpp"
#include "libslic3r/Config.hpp"
#include "libslic3r/ExtrusionRole.hpp"
#include "libslic3r/Geometry.hpp"
#include "libslic3r/GCode/GCodeProcessor.hpp"
#include "libslic3r/GCode/PostProcessor.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/PresetBundle.hpp"
#include "libslic3r/CutUtils.hpp"
#include "libslic3r/ModelArrange.hpp"
#include "libslic3r/Platform.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/SLAPrint.hpp"
#include "libslic3r/Format/AMF.hpp"
#include "libslic3r/Format/3mf.hpp"
#include "libslic3r/Format/STL.hpp"
#include "libslic3r/Format/OBJ.hpp"
#include "libslic3r/PrintConfig.hpp"
#include "libslic3r/Utils.hpp"
#include "libslic3r/Thread.hpp"

#include "PrusaSlicer.hpp"
#include "PrusaSlicerCliSupport.hpp"

#ifdef SLIC3R_GUI
    #include "slic3r/GUI/GUI_Init.hpp"
#endif /* SLIC3R_GUI */

using namespace Slic3r;

namespace Slic3r::CLI_detail {

std::string json_escape(const std::string &value)
{
    constexpr unsigned char kMinPrintableAscii = 0x20;
    constexpr int kUnicodeEscapeHexDigits = 4;
    std::ostringstream out;
    for (const unsigned char ch : value) {
        switch (ch) {
        case '"':  out << "\\\""; break;
        case '\\': out << "\\\\"; break;
        case '\b': out << "\\b"; break;
        case '\f': out << "\\f"; break;
        case '\n': out << "\\n"; break;
        case '\r': out << "\\r"; break;
        case '\t': out << "\\t"; break;
        default:
            if (ch < kMinPrintableAscii)
                out << "\\u" << std::hex << std::setw(kUnicodeEscapeHexDigits) << std::setfill('0') << int(ch) << std::dec;
            else
                out << char(ch);
        }
    }
    return out.str();
}

bool select_profile(PresetCollection &collection, const std::string &name, const char *kind, std::string &error)
{
    if (name.empty())
        return true;
    if (collection.find_preset(name, false, false) == nullptr) {
        error = std::string("Installed ") + kind + " profile not found: " + name;
        return false;
    }
    collection.select_preset_by_name(name, true);
    return true;
}

bool user_profiles_requested(const DynamicPrintAndCLIConfig &config)
{
    return config.opt_bool("load_user_profiles") ||
        config.opt_bool("list_profiles") ||
        !config.opt_string("printer_profile").empty() ||
        !config.opt_string("print_profile").empty() ||
        !config.opt_string("material_profile").empty();
}

#ifdef _WIN32
std::string default_user_data_dir()
{
    const char *root = boost::nowide::getenv("APPDATA");
    return root == nullptr ? std::string() : (boost::filesystem::path(root) / SLIC3R_APP_KEY).string();
}
#elif defined(__APPLE__)
std::string default_user_data_dir()
{
    const char *home = boost::nowide::getenv("HOME");
    if (home == nullptr)
        return {};
    return (boost::filesystem::path(home) / "Library" / "Application Support" / SLIC3R_APP_KEY).string();
}
#else
std::string default_user_data_dir()
{
    if (const char *xdg_config_home = boost::nowide::getenv("XDG_CONFIG_HOME");
        xdg_config_home != nullptr && *xdg_config_home != '\0')
        return (boost::filesystem::path(xdg_config_home) / SLIC3R_APP_KEY).string();
    const char *home = boost::nowide::getenv("HOME");
    if (home == nullptr)
        return {};
    return (boost::filesystem::path(home) / ".config" / SLIC3R_APP_KEY).string();
}
#endif

bool initialize_user_data_dir(AppConfig &app_config, std::string &error)
{
    if (has_data_dir())
        return true;

    const std::string root = default_user_data_dir();
    if (root.empty()) {
        error = "Unable to locate the user configuration directory; pass --datadir explicitly.";
        return false;
    }

    app_config.init_root_data_dir(root);
    if (has_data_dir())
        return true;

    const AppConfig::ConfigurationEntry *best = nullptr;
    for (const AppConfig::ConfigurationEntry &entry : app_config.get_all_slicer_installed()) {
        const boost::filesystem::path path = entry.get_config_path(app_config.get_root_data_dir());
        if (!boost::filesystem::is_directory(path))
            continue;
        if (best == nullptr ||
            (best->version != Semver(SLIC3R_VERSION_FULL) && entry.version == Semver(SLIC3R_VERSION_FULL)) ||
            (best->version != Semver(SLIC3R_VERSION_FULL) && entry.version > best->version))
            best = &entry;
    }

    if (best == nullptr) {
        error = "No installed SuperSlicer user configuration was found; pass --datadir explicitly.";
        return false;
    }

    set_data_dir(best->get_config_path(app_config.get_root_data_dir()).string());
    return true;
}

std::unique_ptr<PresetBundle> load_user_profiles(
    const DynamicPrintAndCLIConfig &config,
    ForwardCompatibilitySubstitutionRule compatibility_rule,
    std::string &error)
{
    try {
        AppConfig app_config(AppConfig::EAppMode::Editor);
        if (!initialize_user_data_dir(app_config, error))
            return {};
        if (std::string load_error = app_config.load(); !load_error.empty()) {
            error = "Unable to load the user application configuration: " + load_error;
            return {};
        }

        auto bundle = std::make_unique<PresetBundle>();
        bundle->load_presets(app_config, compatibility_rule);

        if (!select_profile(bundle->printers, config.opt_string("printer_profile"), "printer", error))
            return {};
        bundle->update_multi_material_filament_presets();
        bundle->update_compatible(PresetSelectCompatibleType::Always);

        const PrinterTechnology technology = bundle->printers.get_edited_preset().printer_technology();
        if (!select_profile(bundle->prints(technology), config.opt_string("print_profile"), "print", error))
            return {};

        const std::string material_name = config.opt_string("material_profile");
        if (!select_profile(bundle->materials(technology), material_name,
                technology == ptFFF ? "filament" : "SLA material", error))
            return {};
        if (technology == ptFFF && !material_name.empty())
            bundle->set_filament_preset(0, material_name);

        bundle->update_compatible(PresetSelectCompatibleType::Never);
        return bundle;
    } catch (const std::exception &ex) {
        error = ex.what();
        return {};
    }
}

void write_profile_collection_json(
    std::ostream &out,
    const PresetCollection &collection,
    const std::string &selected_name)
{
    out << "[";
    bool first = true;
    for (const Preset &preset : collection.get_presets()) {
        if (!first)
            out << ",";
        first = false;
        out << "{"
            << "\"name\":\"" << json_escape(preset.name) << "\","
            << "\"selected\":" << (preset.name == selected_name ? "true" : "false") << ","
            << "\"visible\":" << (preset.is_visible ? "true" : "false") << ","
            << "\"compatible\":" << (preset.is_compatible ? "true" : "false") << ","
            << "\"source\":\"" << (preset.is_default ? "default" : preset.is_system ? "system" : "user") << "\""
            << "}";
    }
    out << "]";
}

void write_profiles_json(std::ostream &out, const PresetBundle &bundle)
{
    out << "{\"schemaVersion\":1,\"active\":{"
        << "\"printer\":\"" << json_escape(bundle.printers.get_selected_preset_name()) << "\","
        << "\"fffPrint\":\"" << json_escape(bundle.fff_prints.get_selected_preset_name()) << "\","
        << "\"slaPrint\":\"" << json_escape(bundle.sla_prints.get_selected_preset_name()) << "\","
        << "\"filament\":\"" << json_escape(bundle.filaments.get_selected_preset_name()) << "\","
        << "\"slaMaterial\":\"" << json_escape(bundle.sla_materials.get_selected_preset_name()) << "\"},";
    out << "\"printers\":";
    write_profile_collection_json(out, bundle.printers, bundle.printers.get_selected_preset_name());
    out << ",\"fffPrints\":";
    write_profile_collection_json(out, bundle.fff_prints, bundle.fff_prints.get_selected_preset_name());
    out << ",\"slaPrints\":";
    write_profile_collection_json(out, bundle.sla_prints, bundle.sla_prints.get_selected_preset_name());
    out << ",\"filaments\":";
    write_profile_collection_json(out, bundle.filaments, bundle.filaments.get_selected_preset_name());
    out << ",\"slaMaterials\":";
    write_profile_collection_json(out, bundle.sla_materials, bundle.sla_materials.get_selected_preset_name());
    out << "}\n";
    out.flush();
}

struct LayerReport
{
    uint16_t id { 0 };
    float z { 0.0f };
    size_t move_count { 0 };
    size_t extrusion_moves { 0 };
    size_t travel_moves { 0 };
    double toolpath_length_mm { 0.0 };
    size_t tool_changes { 0 };
    std::set<uint8_t> extruders;
    std::map<std::string, size_t> roles;
};

std::map<uint16_t, LayerReport> build_layer_reports(const GCodeProcessorResult &result)
{
    std::map<uint16_t, LayerReport> layers;
    for (size_t index = 1; index < result.moves.size(); ++index) {
        const GCodeProcessorResult::MoveVertex &move = result.moves[index];
        if (move.type == EMoveType::Tool_change) {
            ++layers[move.layer_id].tool_changes;
            continue;
        }
        if (move.type != EMoveType::Extrude && move.type != EMoveType::Travel && move.type != EMoveType::Wipe)
            continue;

        LayerReport &layer = layers[move.layer_id];
        layer.id = move.layer_id;
        layer.z = move.position.z();
        ++layer.move_count;
        if (move.type == EMoveType::Extrude) {
            ++layer.extrusion_moves;
            layer.extruders.insert(move.extruder_id);
            ++layer.roles[gcode_extrusion_role_to_string(move.extrusion_role)];
            const Vec3f delta = move.position - result.moves[index - 1].position;
            layer.toolpath_length_mm += std::hypot(double(delta.x()), double(delta.y()));
        } else if (move.type == EMoveType::Travel) {
            ++layer.travel_moves;
        }
    }
    return layers;
}

bool ensure_output_parent(const std::string &path, std::string &error)
{
    try {
        const boost::filesystem::path parent = boost::filesystem::path(path).parent_path();
        if (!parent.empty())
            boost::filesystem::create_directories(parent);
        return true;
    } catch (const std::exception &ex) {
        error = ex.what();
        return false;
    }
}

bool write_slice_report(
    const GCodeProcessorResult &result,
    const DynamicPrintConfig &config,
    const std::string &path,
    std::string &error)
{
    if (!ensure_output_parent(path, error))
        return false;
    boost::nowide::ofstream out(path);
    if (!out) {
        error = "Unable to open slice report for writing: " + path;
        return false;
    }

    const std::map<uint16_t, LayerReport> layers = build_layer_reports(result);
    float min_x = std::numeric_limits<float>::infinity();
    float min_y = std::numeric_limits<float>::infinity();
    float max_x = -std::numeric_limits<float>::infinity();
    float max_y = -std::numeric_limits<float>::infinity();
    size_t extrusion_move_count = 0;
    size_t tool_change_count = 0;
    std::set<uint8_t> used_extruders;
    for (const GCodeProcessorResult::MoveVertex &move : result.moves) {
        if (move.type == EMoveType::Tool_change)
            ++tool_change_count;
        if (move.type != EMoveType::Extrude)
            continue;
        ++extrusion_move_count;
        used_extruders.insert(move.extruder_id);
        min_x = std::min(min_x, move.position.x());
        min_y = std::min(min_y, move.position.y());
        max_x = std::max(max_x, move.position.x());
        max_y = std::max(max_y, move.position.y());
    }

    std::string printer_profile = result.settings_ids.printer;
    std::string print_profile = result.settings_ids.print;
    std::vector<std::string> filament_profiles = result.settings_ids.filament;
    if (printer_profile.empty())
        if (const auto *option = config.option<ConfigOptionString>("printer_settings_id"); option != nullptr)
            printer_profile = option->value;
    if (print_profile.empty())
        if (const auto *option = config.option<ConfigOptionString>("print_settings_id"); option != nullptr)
            print_profile = option->value;
    if (filament_profiles.empty())
        if (const auto *option = config.option<ConfigOptionStrings>("filament_settings_id"); option != nullptr)
            filament_profiles = option->get_values();

    constexpr int kJsonFloatPrecision = 6;
    out << std::fixed << std::setprecision(kJsonFloatPrecision)
        << "{\"schemaVersion\":1,"
        << "\"gcode\":\"" << json_escape(result.filename) << "\","
        << "\"profiles\":{\"printer\":\"" << json_escape(printer_profile)
        << "\",\"print\":\"" << json_escape(print_profile) << "\",\"filaments\":[";
    for (size_t index = 0; index < filament_profiles.size(); ++index) {
        if (index != 0)
            out << ",";
        out << "\"" << json_escape(filament_profiles[index]) << "\"";
    }
    out << "]},\"summary\":{"
        << "\"layerCount\":" << layers.size() << ","
        << "\"moveCount\":" << result.moves.size() << ","
        << "\"extrusionMoveCount\":" << extrusion_move_count << ","
        << "\"estimatedTimeSeconds\":"
        << result.print_statistics.modes[size_t(PrintEstimatedStatistics::ETimeMode::Normal)].time << ","
        << "\"toolChangeCount\":" << tool_change_count << ","
        << "\"usedExtruders\":[";
    for (auto it = used_extruders.begin(); it != used_extruders.end(); ++it)
        out << (it == used_extruders.begin() ? "" : ",") << int(*it);
    out << "]},"
        << "\"bounds\":";
    if (extrusion_move_count == 0)
        out << "null";
    else
        out << "{\"minX\":" << min_x << ",\"minY\":" << min_y
            << ",\"maxX\":" << max_x << ",\"maxY\":" << max_y << "}";

    out << ",\"bedShape\":[";
    for (size_t index = 0; index < result.bed_shape.size(); ++index) {
        if (index != 0)
            out << ",";
        out << "[" << result.bed_shape[index].x() << "," << result.bed_shape[index].y() << "]";
    }
    out << "],\"layers\":[";
    bool first_layer = true;
    for (const auto &[id, layer] : layers) {
        if (!first_layer)
            out << ",";
        first_layer = false;
        out << "{\"id\":" << id << ",\"z\":" << layer.z
            << ",\"moveCount\":" << layer.move_count
            << ",\"extrusionMoves\":" << layer.extrusion_moves
            << ",\"travelMoves\":" << layer.travel_moves
            << ",\"toolpathLengthMm\":" << layer.toolpath_length_mm
            << ",\"toolChanges\":" << layer.tool_changes
            << ",\"extruders\":[";
        for (auto it = layer.extruders.begin(); it != layer.extruders.end(); ++it)
            out << (it == layer.extruders.begin() ? "" : ",") << int(*it);
        out << "],\"roles\":{";
        bool first_role = true;
        for (const auto &[role, count] : layer.roles) {
            if (!first_role)
                out << ",";
            first_role = false;
            out << "\"" << json_escape(role) << "\":" << count;
        }
        out << "}}";
    }
    out << "]}\n";
    return true;
}

const char *role_color(GCodeExtrusionRole role)
{
    switch (role) {
    case GCodeExtrusionRole::ExternalPerimeter:        return "#ef4444";
    case GCodeExtrusionRole::Perimeter:                return "#f97316";
    case GCodeExtrusionRole::OverhangPerimeter:        return "#ec4899";
    case GCodeExtrusionRole::InternalInfill:           return "#3b82f6";
    case GCodeExtrusionRole::SolidInfill:              return "#06b6d4";
    case GCodeExtrusionRole::TopSolidInfill:           return "#14b8a6";
    case GCodeExtrusionRole::BridgeInfill:
    case GCodeExtrusionRole::InternalBridgeInfill:     return "#8b5cf6";
    case GCodeExtrusionRole::SupportMaterial:          return "#84cc16";
    case GCodeExtrusionRole::SupportMaterialInterface: return "#22c55e";
    case GCodeExtrusionRole::Skirt:                    return "#eab308";
    case GCodeExtrusionRole::GapFill:
    case GCodeExtrusionRole::ThinWall:                 return "#f59e0b";
    case GCodeExtrusionRole::WipeTower:                return "#64748b";
    default:                                           return "#94a3b8";
    }
}

bool write_slice_preview(
    const GCodeProcessorResult &result,
    const std::string &path,
    int requested_layer,
    std::string &error)
{
    std::set<uint16_t> extrusion_layers;
    for (const GCodeProcessorResult::MoveVertex &move : result.moves)
        if (move.type == EMoveType::Extrude)
            extrusion_layers.insert(move.layer_id);
    if (extrusion_layers.empty()) {
        error = "The processed G-code contains no extrusion layers.";
        return false;
    }

    constexpr size_t median_divisor = 2;
    uint16_t layer_id = 0;
    if (requested_layer < 0) {
        auto middle = extrusion_layers.begin();
        std::advance(middle, extrusion_layers.size() / median_divisor);
        layer_id = *middle;
    } else if (requested_layer > std::numeric_limits<uint16_t>::max() ||
               extrusion_layers.count(uint16_t(requested_layer)) == 0) {
        error = "Requested preview layer is not present in the processed G-code: " + std::to_string(requested_layer);
        return false;
    } else {
        layer_id = uint16_t(requested_layer);
    }

    float min_x = std::numeric_limits<float>::infinity();
    float min_y = std::numeric_limits<float>::infinity();
    float max_x = -std::numeric_limits<float>::infinity();
    float max_y = -std::numeric_limits<float>::infinity();
    float layer_z = 0.0f;
    for (size_t index = 1; index < result.moves.size(); ++index) {
        const GCodeProcessorResult::MoveVertex &move = result.moves[index];
        if (move.type != EMoveType::Extrude || move.layer_id != layer_id)
            continue;
        const Vec3f &start = result.moves[index - 1].position;
        min_x = std::min({ min_x, start.x(), move.position.x() });
        min_y = std::min({ min_y, start.y(), move.position.y() });
        max_x = std::max({ max_x, start.x(), move.position.x() });
        max_y = std::max({ max_y, start.y(), move.position.y() });
        layer_z = move.position.z();
    }

    if (!ensure_output_parent(path, error))
        return false;
    boost::nowide::ofstream out(path);
    if (!out) {
        error = "Unable to open slice preview for writing: " + path;
        return false;
    }

    constexpr float padding_side_count = 2.0f;
    constexpr float maximum_preview_width = 2.0f;
    constexpr int coordinate_decimal_places = 4;
    const float content_width = std::max(max_x - min_x, 1.0f);
    const float content_height = std::max(max_y - min_y, 1.0f);
    const float padding = std::max(content_width, content_height) * 0.04f;
    const float view_min_x = min_x - padding;
    const float view_min_y = min_y - padding;
    const float view_width = content_width + padding_side_count * padding;
    const float view_height = content_height + padding_side_count * padding;

    out << std::fixed << std::setprecision(coordinate_decimal_places)
        << "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"" << view_min_x << " " << view_min_y
        << " " << view_width << " " << view_height << "\" width=\"1000\" height=\"1000\">\n"
        << "<title>SuperSlicer layer " << layer_id << " at Z " << layer_z << " mm</title>\n"
        << "<rect x=\"" << view_min_x << "\" y=\"" << view_min_y << "\" width=\"" << view_width
        << "\" height=\"" << view_height << "\" fill=\"#0f172a\"/>\n"
        << "<g transform=\"translate(0 " << (min_y + max_y) << ") scale(1 -1)\" "
        << "stroke-linecap=\"round\" stroke-linejoin=\"round\" fill=\"none\">\n";
    for (size_t index = 1; index < result.moves.size(); ++index) {
        const GCodeProcessorResult::MoveVertex &move = result.moves[index];
        if (move.type != EMoveType::Extrude || move.layer_id != layer_id)
            continue;
        const Vec3f &start = result.moves[index - 1].position;
        const float width = std::clamp(move.width, 0.08f, maximum_preview_width);
        out << "<line x1=\"" << start.x() << "\" y1=\"" << start.y()
            << "\" x2=\"" << move.position.x() << "\" y2=\"" << move.position.y()
            << "\" stroke=\"" << role_color(move.extrusion_role) << "\" stroke-width=\"" << width << "\"/>\n";
    }
    out << "</g>\n</svg>\n";
    return true;
}

bool write_requested_slice_artifacts(
    const GCodeProcessorResult &result,
    const DynamicPrintConfig &config,
    const std::string &report_path,
    const std::string &preview_path,
    int preview_layer)
{
    std::string error;
    if (!report_path.empty() && !write_slice_report(result, config, report_path, error)) {
        boost::nowide::cerr << "Unable to write slice report: " << error << std::endl;
        return false;
    }
    if (!preview_path.empty() && !write_slice_preview(result, preview_path, preview_layer, error)) {
        boost::nowide::cerr << "Unable to write slice preview: " << error << std::endl;
        return false;
    }
    return true;
}

} // namespace Slic3r::CLI_detail
