#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem.hpp>
#include <boost/format.hpp>
#include <boost/nowide/args.hpp>
#include <boost/nowide/cenv.hpp>
#include <boost/nowide/fstream.hpp>
#include <boost/nowide/iostream.hpp>
#include <boost/nowide/integration/filesystem.hpp>
#include <boost/dll/runtime_symbol_info.hpp>

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <limits>
#include <map>
#include <memory>
#include <set>
#include <sstream>

#include "unix/fhs.hpp"  // Generated by CMake from ../platform/unix/fhs.hpp.in

#include "libslic3r/libslic3r.h"
#if ENABLE_GL_CORE_PROFILE
#include <boost/algorithm/string/split.hpp>
#endif // ENABLE_GL_CORE_PROFILE
#include "libslic3r/AppConfig.hpp"
#include "libslic3r/Config.hpp"
#include "libslic3r/ExtrusionRole.hpp"
#include "libslic3r/Geometry.hpp"
#include "libslic3r/GCode/GCodeProcessor.hpp"
#include "libslic3r/GCode/PostProcessor.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/PresetBundle.hpp"
#include "libslic3r/CutUtils.hpp"
#include "libslic3r/ModelArrange.hpp"
#include "libslic3r/Platform.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/SLAPrint.hpp"
#include "libslic3r/Format/AMF.hpp"
#include "libslic3r/Format/3mf.hpp"
#include "libslic3r/Format/STL.hpp"
#include "libslic3r/Format/OBJ.hpp"
#include "libslic3r/PrintConfig.hpp"
#include "libslic3r/Utils.hpp"
#include "libslic3r/Thread.hpp"

#include "PrusaSlicer.hpp"

#ifdef SLIC3R_GUI
    #include "slic3r/GUI/GUI_Init.hpp"
#endif /* SLIC3R_GUI */
#include "PrusaSlicerCliSupport.hpp"

using namespace Slic3r;

namespace Slic3r::CLI_detail {
PrinterTechnology get_printer_technology(const DynamicConfig &config)
{
    const ConfigOptionEnum<PrinterTechnology> *opt = config.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
    return (opt == nullptr) ? ptUnknown : opt->value;
}

static bool duplicate_for_cli(Model &model, size_t copies, const arr2::ArrangeBed &bed,
                              const arr2::ArrangeSettingsView &settings)
{
    try {
        duplicate(model, copies, bed, settings);
        return true;
    } catch (const std::exception &ex) {
        boost::nowide::cerr << "error: " << ex.what() << std::endl;
        return false;
    }
}

static bool rename_output_for_cli(std::string &output_path, const std::string &final_path)
{
    if (output_path == final_path)
        return true;
    if (Slic3r::rename_file(output_path, final_path)) {
        boost::nowide::cerr << "Renaming file " << output_path << " to " << final_path << " failed" << std::endl;
        return false;
    }
    output_path = final_path;
    return true;
}

#if defined(SLIC3R_GUI) && ENABLE_GL_CORE_PROFILE
std::pair<int, int> parse_requested_opengl_version(const std::string& version_text)
{
    constexpr int minimum_opengl_major = 3;
    constexpr int minimum_opengl_minor = 2;
    const Semver minimum_version(minimum_opengl_major, minimum_opengl_minor, 0, 0);
    const std::optional<Semver> version = Semver::parse(version_text);
    if (!version.has_value() || *version < minimum_version) {
        boost::nowide::cerr << "Required OpenGL version " << version_text
            << " is invalid. Must be greater than or equal to " << minimum_version.to_string()
            << "\n Option 'opengl-version' ignored." << std::endl;
        return {0, 0};
    }

    const std::pair<int, int> requested{version->maj(), version->min()};
    if (std::find(Slic3r::GUI::OpenGLVersions::core.begin(),
                  Slic3r::GUI::OpenGLVersions::core.end(),
                  requested) != Slic3r::GUI::OpenGLVersions::core.end())
        return requested;

    boost::nowide::cerr << "Required OpenGL version " << version_text
        << " not recognized.\n Option 'opengl-version' ignored." << std::endl;
    return {0, 0};
}
#endif

static bool read_model_file_for_cli(
    const std::string& file,
    DynamicPrintConfig& file_config,
    ConfigSubstitutionContext& substitutions,
    Model& model)
{
    try {
        model = Model::read_from_file(
            file,
            &file_config,
            &substitutions,
            Model::LoadAttribute::AddDefaultInstances | Model::LoadAttribute::CheckVersion);
        return true;
    } catch (const std::exception& ex) {
        boost::nowide::cerr << file << ": " << ex.what() << std::endl;
        return false;
    }
}

static void print_cli_config_substitutions(
    const std::string& file,
    const ConfigSubstitutions& substitutions)
{
    if (substitutions.empty())
        return;

    boost::nowide::cout << "The following configuration values were substituted when loading \""
        << file << "\":\n";
    for (const ConfigSubstitution& substitution : substitutions) {
        if (substitution.opt_def) {
            boost::nowide::cout << "\tkey = \"" << substitution.opt_def->opt_key
                << "\"\t loaded = \"" << substitution.old_value << "\tsubstituted = \""
                << substitution.new_value->serialize() << "\"\n";
        } else {
            boost::nowide::cout << "\tkey = \"" << substitution.old_name
                << "\"\t can't be loaded (value = \"" << substitution.old_value << "\")\n";
        }
    }
}

CliModelLoadResult load_model_for_cli(
    const std::string& file,
    ForwardCompatibilitySubstitutionRule substitution_rule,
    PrinterTechnology& printer_technology,
    DynamicPrintConfig& print_config,
    Model& model)
{
    DynamicPrintConfig file_config;
    ConfigSubstitutionContext substitutions(substitution_rule);
    if (!read_model_file_for_cli(file, file_config, substitutions, model))
        return CliModelLoadResult::error;

    const PrinterTechnology file_technology = get_printer_technology(file_config);
    if (printer_technology == ptUnknown)
        printer_technology = file_technology;
    else if (printer_technology != file_technology && file_technology != ptUnknown) {
        boost::nowide::cerr << "Mixing configurations for FFF and SLA technologies" << std::endl;
        return CliModelLoadResult::error;
    }

    print_cli_config_substitutions(file, substitutions.get());
    file_config += std::move(print_config);
    print_config = std::move(file_config);

    if (!model.objects.empty())
        return CliModelLoadResult::loaded;

    boost::nowide::cerr << "Error: file is empty: " << file << std::endl;
    return CliModelLoadResult::empty;
}

static std::vector<double> resized_wipe_extruder_values(
    const ConfigOptionFloats& option,
    unsigned int extruder_count)
{
    constexpr size_t values_per_extruder = 2;
    constexpr double default_wipe_volume_mm3 = 50.;
    std::vector<double> values = option.get_values();
    while (values.size() < values_per_extruder * extruder_count) {
        values.push_back(values.size() > 1 ? values[0] : default_wipe_volume_mm3);
        values.push_back(values.size() > 1 ? values[1] : default_wipe_volume_mm3);
    }
    values.resize(values_per_extruder * extruder_count);
    return values;
}

static std::vector<double> resized_wiping_matrix(
    const std::vector<double>& old_matrix,
    size_t old_extruder_count,
    const std::vector<double>& wipe_values,
    unsigned int extruder_count)
{
    constexpr size_t values_per_extruder = 2;
    std::vector<double> matrix;
    matrix.reserve(extruder_count * extruder_count);
    for (unsigned int from = 0; from < extruder_count; ++from) {
        for (unsigned int to = 0; to < extruder_count; ++to) {
            if (from < old_extruder_count && to < old_extruder_count)
                matrix.push_back(old_matrix[from * old_extruder_count + to]);
            else if (from == to)
                matrix.push_back(0.);
            else
                matrix.push_back(wipe_values[values_per_extruder * from] +
                    wipe_values[values_per_extruder * to + 1]);
        }
    }
    return matrix;
}

void configure_cli_extruders(DynamicPrintConfig& print_config, unsigned int extruder_count)
{
    print_config.set_num_extruders(extruder_count);
    for (const std::string& key : Preset::filament_options()) {
        ConfigOption* option = print_config.option(key);
        if (option != nullptr && option->is_vector())
            static_cast<ConfigOptionVectorBase*>(option)->resize(extruder_count);
    }

    ConfigOptionFloats* matrix_option =
        print_config.option<ConfigOptionFloats>("wiping_volumes_matrix");
    ConfigOptionFloats* wipe_option =
        print_config.option<ConfigOptionFloats>("wiping_volumes_extruders");
    if (matrix_option == nullptr || wipe_option == nullptr)
        return;

    const std::vector<double> old_matrix = matrix_option->get_values();
    const size_t old_extruder_count =
        size_t(std::sqrt(double(old_matrix.size())) + EPSILON);
    if (old_extruder_count == extruder_count)
        return;

    const std::vector<double> wipe_values =
        resized_wipe_extruder_values(*wipe_option, extruder_count);
    wipe_option->set(wipe_values);
    matrix_option->set(resized_wiping_matrix(
        old_matrix, old_extruder_count, wipe_values, extruder_count));
}

void merge_cli_models(std::vector<Model>& models)
{
    Model merged;
    for (Model& model : models)
        for (ModelObject* object : model.objects)
            merged.add_object(*object);
    models.clear();
    models.emplace_back(std::move(merged));
}

void prepare_cli_duplicates(std::vector<Model>& models)
{
    for (Model& model : models) {
        const bool all_objects_have_instances = std::none_of(
            model.objects.begin(), model.objects.end(),
            [](ModelObject* object) { return object->instances.empty(); });
        if (!all_objects_have_instances)
            model.add_default_instances();
    }
}

static void center_cli_model(Model& model, const Vec2d& center)
{
    model.add_default_instances();
    model.center_instances_around_point(center);

    BoundingBoxf3 bounding_box;
    for (ModelObject* object : model.objects)
        bounding_box.merge(object->instance_bounding_box(0, false));
    for (ModelObject* object : model.objects)
        for (ModelInstance* instance : object->instances)
            instance->set_offset(
                Z, instance->get_offset(Z) - bounding_box.min.z());
}

void center_cli_models(std::vector<Model>& models, const Vec2d& center)
{
    for (Model& model : models)
        center_cli_model(model, center);
}

void align_cli_models(std::vector<Model>& models, const Vec2d& point)
{
    for (Model& model : models) {
        const BoundingBoxf3 bounding_box = model.bounding_box_exact();
        model.translate(
            -(bounding_box.min.x() - point.x()),
            -(bounding_box.min.y() - point.y()),
            -bounding_box.min.z());
    }
}


void scale_cli_models(std::vector<Model>& models, double factor)
{
    for (Model& model : models)
        for (ModelObject* object : model.objects)
            object->scale(factor);
}

bool scale_cli_models_to_fit(
    std::vector<Model>& models, const Vec3d& volume)
{
    if (volume.x() <= 0 || volume.y() <= 0 || volume.z() <= 0) {
        boost::nowide::cerr << "--scale-to-fit requires a positive volume" << std::endl;
        return false;
    }
    for (Model& model : models)
        for (ModelObject* object : model.objects)
            object->scale_to_fit(volume);
    return true;
}

static void cut_front_cli_object(Model& model, double height)
{
    Cut cut(
        model.objects.front(),
        0,
        Geometry::translation_transform(height * Vec3d::UnitZ()),
        ModelObjectCutAttribute::KeepLower |
            ModelObjectCutAttribute::KeepUpper |
            ModelObjectCutAttribute::PlaceOnCutUpper);
    const ModelObjectPtrs& cut_objects = cut.perform_with_plane();
    for (ModelObject* object : cut_objects)
        model.add_object(*object);
    model.delete_object(size_t(0));
}

void cut_cli_models(std::vector<Model>& models, double height)
{
    for (Model& model : models) {
        model.translate(0, 0, -model.bounding_box_exact().min.z());
        const size_t object_count = model.objects.size();
        for (size_t index = 0; index < object_count; ++index)
            cut_front_cli_object(model, height);
    }

    // Preserve the existing CLI cut behavior: the branch replaces the source model list
    // with its (currently unpopulated) result collection.
    std::vector<Model> cut_models;
    models = std::move(cut_models);
}

void split_cli_models(std::vector<Model>& models)
{
    for (Model& model : models) {
        const size_t object_count = model.objects.size();
        for (size_t index = 0; index < object_count; ++index) {
            ModelObjectPtrs split_objects;
            model.objects.front()->split(&split_objects);
            model.delete_object(size_t(0));
        }
    }
}

void ensure_cli_models_on_bed(std::vector<Model>& models)
{
    for (Model& model : models)
        for (ModelObject* object : model.objects)
            object->ensure_on_bed();
}

void request_default_stl_export(std::vector<std::string>& actions)
{
    if (actions.empty())
        actions.emplace_back("export_stl");
}

static void report_sla_slicing_status(const PrintBase::SlicingStatus& status)
{
    if (status.percent < 0)
        return;

    std::string status_text = status.main_text;
    if (!status.args.empty()) {
        boost::format formatter(status_text);
        for (const std::string& argument : status.args)
            formatter % argument;
        status_text = formatter.str();
    }
    printf("%3d%s %s\n", status.percent, "% =>", status_text.c_str());
}

static bool arrange_cli_model(
    Model& model,
    const DynamicPrintAndCLIConfig& cli_config,
    const DynamicPrintConfig& print_config,
    int duplicate_count,
    bool user_center_specified,
    const arr2::ArrangeBed& bed)
{
    if (cli_config.opt_bool("dont_arrange"))
        return true;

    arr2::ArrangeSettings arrange_settings;
    arrange_settings.set_distance_from_objects(
        min_object_distance(static_cast<const ConfigBase*>(&print_config)));
    if (duplicate_count > 1 &&
        !duplicate_for_cli(
            model, static_cast<size_t>(duplicate_count), bed, arrange_settings))
        return false;

    if (user_center_specified) {
        const Vec2d center =
            cli_config.option<ConfigOptionPoint>("center")->value;
        arrange_objects(
            model, arr2::InfiniteBed{scaled(center)}, arrange_settings);
    } else {
        arrange_objects(model, bed, arrange_settings);
    }
    return true;
}

static void auto_assign_cli_extruders(Model& model, Print& print)
{
    for (ModelObject* object : model.objects)
        print.auto_assign_extruders(object);
}

static bool export_cli_print_unchecked(
    PrinterTechnology printer_technology,
    PrintBase& print,
    Print& fff_print,
    SLAPrint& sla_print,
    const DynamicPrintAndCLIConfig& cli_config,
    const DynamicPrintConfig& print_config,
    bool slice_for_gcodeviewer,
    std::vector<std::string>& gcodeviewer_input_files,
    std::string& output_path)
{
    std::string final_path;
    print.process();
    if (printer_technology == ptFFF) {
        GCodeProcessorResult processed_result;
        GCodeProcessorResult* result =
            cli_config.opt_string("slice_report").empty() &&
            cli_config.opt_string("slice_preview").empty() ?
                nullptr : &processed_result;
        output_path = fff_print.export_gcode(output_path, result, nullptr);
        final_path =
            fff_print.print_statistics().finalize_output_path(output_path);
        if (result != nullptr && !write_requested_slice_artifacts(
                *result,
                print_config,
                cli_config.opt_string("slice_report"),
                cli_config.opt_string("slice_preview"),
                cli_config.opt_int("slice_preview_layer")))
            return false;
    } else {
        output_path = sla_print.output_filepath(output_path);
        final_path =
            sla_print.print_statistics().finalize_output_path(output_path);
        sla_print.export_print(final_path);
    }

    if (!rename_output_for_cli(output_path, final_path))
        return false;
    run_post_process_scripts(output_path, fff_print.full_print_config());
    if (slice_for_gcodeviewer && printer_technology == ptFFF)
        gcodeviewer_input_files.emplace_back(output_path);
    boost::nowide::cout << "Slicing result exported to " << output_path << std::endl;
    return true;
}

static bool export_cli_print(
    PrinterTechnology printer_technology,
    PrintBase& print,
    Print& fff_print,
    SLAPrint& sla_print,
    const DynamicPrintAndCLIConfig& cli_config,
    const DynamicPrintConfig& print_config,
    bool slice_for_gcodeviewer,
    std::vector<std::string>& gcodeviewer_input_files,
    std::string& output_path)
{
    try {
        return export_cli_print_unchecked(
            printer_technology,
            print,
            fff_print,
            sla_print,
            cli_config,
            print_config,
            slice_for_gcodeviewer,
            gcodeviewer_input_files,
            output_path);
    } catch (const std::exception& ex) {
        boost::nowide::cerr << ex.what() << std::endl;
        return false;
    }
}

static bool process_cli_model(
    Model& model,
    PrinterTechnology printer_technology,
    const DynamicPrintAndCLIConfig& cli_config,
    const DynamicPrintConfig& print_config,
    int duplicate_count,
    bool user_center_specified,
    const arr2::ArrangeBed& bed,
    bool slice_for_gcodeviewer,
    std::vector<std::string>& gcodeviewer_input_files)
{
    std::string output_path = cli_config.opt_string("output");
    Print fff_print;
    SLAPrint sla_print;
    sla_print.set_status_callback(report_sla_slicing_status);

    PrintBase* print = printer_technology == ptFFF ?
        static_cast<PrintBase*>(&fff_print) :
        static_cast<PrintBase*>(&sla_print);
    if (!arrange_cli_model(
            model,
            cli_config,
            print_config,
            duplicate_count,
            user_center_specified,
            bed))
        return false;

    if (printer_technology == ptFFF)
        auto_assign_cli_extruders(model, fff_print);
    print->apply(model, print_config);
    const auto validation = print->validate();
    if (validation.first != PrintBase::PrintValidationError::pveNone) {
        boost::nowide::cerr << validation.second << std::endl;
        return false;
    }
    if (print->empty()) {
        boost::nowide::cout << "Nothing to print for " << output_path
            << " . Either the print is empty or no object is fully inside the print volume."
            << std::endl;
        return true;
    }
    return export_cli_print(
        printer_technology,
        *print,
        fff_print,
        sla_print,
        cli_config,
        print_config,
        slice_for_gcodeviewer,
        gcodeviewer_input_files,
        output_path);
}

bool process_cli_models(
    std::vector<Model>& models,
    bool make_copy,
    PrinterTechnology printer_technology,
    const DynamicPrintAndCLIConfig& cli_config,
    const DynamicPrintConfig& print_config,
    int duplicate_count,
    bool user_center_specified,
    const arr2::ArrangeBed& bed,
    bool slice_for_gcodeviewer,
    std::vector<std::string>& gcodeviewer_input_files)
{
    Model model_copy;
    for (Model& source_model : models) {
        if (make_copy)
            model_copy = source_model;
        Model& model = make_copy ? model_copy : source_model;
        if (!process_cli_model(
                model,
                printer_technology,
                cli_config,
                print_config,
                duplicate_count,
                user_center_specified,
                bed,
                slice_for_gcodeviewer,
                gcodeviewer_input_files))
            return false;
    }
    return true;
}

#if !defined(_WIN32) && !defined(__APPLE__)
boost::filesystem::path appimage_install_path(
    const boost::filesystem::path& fallback)
{
    const char* appimage_env = std::getenv("APPIMAGE");
    if (appimage_env == nullptr || appimage_env[0] == '\0')
        return fallback;

    try {
        const boost::filesystem::path appimage_path =
            boost::filesystem::canonical(boost::filesystem::path(appimage_env));
        if (!boost::filesystem::exists(appimage_path))
            return fallback;
        BOOST_LOG_TRIVIAL(trace) << "appimage detected, change install path from '"
            << fallback << "' to '" << appimage_env << "\n";
        return appimage_path;
    } catch (const std::exception&) {
        return fallback;
    }
}
#endif

} // namespace Slic3r::CLI_detail
